# LINKS -------------------------------------------------------------------
# Dataset: https://data.cms.gov/provider-characteristics/hospitals-and-other-facilities/provider-of-services-file-quality-improvement-and-evaluation-system
# Dictionary: https://data.cms.gov/sites/default/files/2023-07/0ca58d5d-7914-4532-b22d-41741d3e6151/P.QWB.POSQ.OTHER.LAYOUT.MAR23.pdf
#
# Provider of Services File - Quality Improvement and Evaluation System A
# dataset that provides information on non-laboratory provider types including
# demographic information and the type of services provided.
#
# Please be advised that as of Q1 2026, Portable X-ray (PXR), End-Stage Renal
# Disease (ESRD), Intermediate Care Facilities for Individuals with Intellectual
# Disabilities (ICF/IID), Outpatient Physical Therapy/Speech Language Pathology
# (OPT/SLP) and Comprehensive Outpatient Rehabilitation Facility (CORF)
# providers are now available in the iQIES Provider of Service file.
#
# The Provider of Services File (POS) - Quality Improvement and Evaluation
# System (QIES) data provides provider demographic and associated certification
# information for hospital & non-hospital facilities along with the provider
# number (CMS Certification Number), name, address, and other characteristics of
# the participating providers.
#
# This data is gathered as part of the CMS Provider Certification process and is
# updated each time a provider is re-certified.  The specific time table for each
# provider types re-certification process does vary.

# LOOKUPS --------------------------------------------------------
## PRVDR_CTGRY_SBTYP_CD ----------------------------------------------------
## Provider Category Subtype Code: Identifies the subtype of the provider, within
## the primary category. Used in reporting to show the breakdown of provider
## categories, mainly for hospitals and SNFs.
list(
  "01" = "Short Term",
  "02" = "Long Term",
  "03" = "Religious Non-Medical Health Care Institutions",
  "04" = "Psychiatric",
  "05" = "Rehabilitation",
  "06" = "Childrens Hospitals",
  "07" = "Distinct Part Psychiatric Hospital",
  "11" = "Critical Access Hospitals",
  "20" = "Transplant Hospitals",
  "22" = "Medicaid Only Short-Term Hospitals",
  "23" = "Medicaid Only Childrens Hospitals",
  "24" = "Medicaid Only Children's Psychiatric",
  "25" = "Medicaid Only Psychiatric Hospitals",
  "26" = "Medicaid Only Rehabilitation Hospitals",
  "27" = "Medicaid Only Long-Term Hospitals"
)

## GNRL_FAC_TYPE_CD --------------------------------------------------------
## Category-specific Facility Type Code: Indicates the category-specific
## facility type code, for certain provider categories only.
list(
  "01" = "Short-Term",
  "02" = "Long-Term",
  "03" = "Religious Non-Medical Health Care Institution",
  "04" = "Psychiatric",
  "05" = "Rehabilitation",
  "06" = "Childrens",
  "07" = "Distinct Part Psychiatric Hospital",
  "11" = "Critical Access Hospitals",
  "12" = "Rural Emergency Hospitals",
)

## PGM_TRMNTN_CD ----------------------------------------------------
# Termination Code: Indicates the current termination status for the provider.
list(
  "00" = "ACTIVE PROVIDER",
  "01" = "VOLUNTARY-MERGER, CLOSURE",
  "02" = "VOLUNTARY-DISSATISFACTION WITH REIMBURSEMENT",
  "03" = "VOLUNTARY-RISK OF INVOLUNTARY TERMINATION",
  "04" = "VOLUNTARY-OTHER REASON FOR WITHDRAWAL",
  "05" = "INVOLUNTARY-FAILURE TO MEET HEALTH/SAFETY REQ",
  "06" = "INVOLUNTARY-FAILURE TO MEET AGREEMENT",
  "07" = "OTHER-PROVIDER STATUS CHANGE",
  "08" = "NONPAYMENT OF FEES - CLIA Only",
  "09" = "REV/UNSUCCESSFUL PARTICIPATION IN PT - CLIA Only",
  "10" = "REV/OTHER REASON - CLIA Only",
  "11" = "INCOMPLETE CLIA APPLICATION INFORMATION - CLIA Only",
  "12" = "NO LONGER PERFORMING TESTS - CLIA Only",
  "13" = "MULTIPLE TO SINGLE SITE CERTIFICATE - CLIA Only",
  "14" = "SHARED LABORATORY - CLIA Only",
  "15" = "FAILURE TO RENEW WAIVER PPM CERTIFICATE - CLIA Only",
  "16" = "DUPLICATE CLIA NUMBER - CLIA Only",
  "17" = "MAIL RETURNED NO FORWARD ADDRESS CERT ENDED - CLIA Only",
  "20" = "NOTIFICATION BANKRUPTCY - CLIA Only",
  "33" = "ACCREDITATION NOT CONFIRMED - CLIA Only",
  "80" = "AWAITING STATE APPROVAL",
  "99" = "OIG ACTION - DO NOT ACTIVATE - CLIA Only"
)

## GNRL_CNTL_TYPE_CD -------------------------------------------------------
# Ownership Type Code: Indicates the ownership type of the provider.
list(
  "01" = "CHURCH",
  "02" = "PRIVATE (NOT FOR PROFIT)",
  "03" = "OTHER (SPECIFY)",
  "04" = "PRIVATE (FOR PROFIT)",
  "05" = "FEDERAL",
  "06" = "STATE",
  "07" = "LOCAL",
  "08" = "HOSPITAL DISTRICT OR AUTHORITY",
  "09" = "PHYSICIAN OWNERSHIP",
  "10" = "TRIBAL"
)

## ACRDTN_TYPE_CD ----------------------------------------------------------
# Accreditation Type Code: Indicates an accrediting organization deeming the
# provider. If a provider is deemed by multiple accrediting organizations then
# the accrediting organization with the earliest active deeming effective date
# is displayed in this field.
list(
  "0" = "NOT ACCREDITED",
  "1" = "JC",
  "2" = "AOA/HFAP",
  "3" = "DNV",
  "7" = "ACHC",
  "9" = "CIHQ"
)

## CRTFCTN_ACTN_TYPE_CD ----------------------------------------------------
# Type of Action Code: Identifies the reason for the certification.
list(
  "1" = "INITIAL",
  "2" = "RECERTIFICATION",
  "3" = "TERMINATION",
  "4" = "CHANGE OF OWNERSHIP",
  "5" = "VALIDATION",
  "8" = "FULL SURVEY AFTER COMPLAINT"
)

## PHRMCY_SRVC_CD ----------------------------------------------------------
# Pharmacy Code: Indicates how pharmaceutical services are provided.
list(
  "0" = "NOT PROVIDED",
  "1" = "PROVIDED BY STAFF",
  "2" = "PROVIDED UNDER ARRANGEMENT",
  "3" = "PROVIDED BY STAFF AND UNDER ARRANGEMENT"
)

# VARIABLES -------------------------------------------------------------------
list(
  # PRVDR_CTGRY_CD = "01", <==
  # STATE_RGN_CD = "001", <==
  PRVDR_NUM = "ccn",
  PRVDR_CTGRY_SBTYP_CD = "sub_type",
  FAC_NAME = "name",
  ST_ADR = "address",
  CITY_NAME = "city",
  STATE_CD = "state",
  ZIP_CD = "zip",
  CRTFCTN_DT = "cert_date",
  ORGNL_PRTCPTN_DT = "orig_date",
  TRMNTN_EXPRTN_DT = "term_date",
  ELGBLTY_SW = "eligible",
  PGM_TRMNTN_CD = "status",
  ACRDTN_TYPE_CD = "accreditation",
  GNRL_CNTL_TYPE_CD = "own_type",
  CRTFCTN_ACTN_TYPE_CD = "action",
  ## Affiliated Counts -------------------------------------------------------
  TOT_AFLTD_AMBLNC_SRVC_CNT = "ambulance_services",
  TOT_AFLTD_ASC_CNT = "ambulatory_service_centers",
  TOT_COLCTD_HOSP_CNT = "colocated_hospitals",
  TOT_AFLTD_ESRD_CNT = "esrd_units",
  TOT_AFLTD_FQHC_CNT = "fqhcs",
  TOT_AFLTD_HHA_CNT = "hhas",
  TOT_AFLTD_HOSPC_CNT = "hospices",
  TOT_AFLTD_OPO_CNT = "opos",
  TOT_AFLTD_PRTF_CNT = "psychiatric_residential_treatment_facilities",
  TOT_AFLTD_RHC_CNT = "rhcs",
  TOT_AFLTD_SNF_CNT = "snfs",
  AFLTD_PRVDR_CNT = "total_affiliated_providers",
  ## Affiliated Resident Programs [Y/N]--------------------------------------------
  RSDNT_PGM_ALPTHC_SW = "Allopathic",
  RSDNT_PGM_DNTL_SW = "Dental",
  RSDNT_PGM_OSTPTHC_SW = "Osteopathic",
  RSDNT_PGM_OTHR_SW = "Other",
  RSDNT_PGM_PDTRC_SW = "Podiatric",
  ## Services ----------------------------------------------------------------
  "ASC_BGN_SRVC_DT" = "",
  "FREESTNDNG_ASC_SW" = "",
  PHRMCY_SRVC_CD = "srvc_rx",
  LAB_SRVC_CD = "srvc_lab",
  RDLGY_SRVC_CD = "srvc_rad",
  ## Bed Counts --------------------------------------------------------------
  OVRRD_BED_CNT_SW = "bed_override",
  CRTFD_BED_CNT = "bed_cert",
  ICFIID_BED_CNT = "bed_icfiid",
  MDCD_NF_BED_CNT = "bed_nf_caid",
  MDCR_SNF_BED_CNT = "bed_snf_care",
  MDCR_MDCD_SNF_BED_CNT = "bed_snf_dual",
  AIDS_BED_CNT = "bed_aids",
  ALZHMR_BED_CNT = "bed_alz",
  DLYS_BED_CNT = "bed_esrd",
  DSBL_CHLDRN_BED_CNT = "bed_disabled",
  HEAD_TRMA_BED_CNT = "bed_head",
  HOSPC_BED_CNT = "bed_hospice",
  HNTGTN_DEASE_BED_CNT = "bed_hunt",
  REHAB_BED_CNT = "bed_rehab",
  VNTLTR_BED_CNT = "bed_vent",
  BED_CNT = "bed_total",
  "BRNCH_CNT" = "",
  "BRNCH_OPRTN_SW" = "",
  "CAH_PSYCH_DPU_SW" = "N",
  "CAH_REHAB_DPU_SW" = "Y",
  "CAH_SB_SW" = "N",
  "CRDC_CTHRTZTN_PRCDR_ROOMS_CNT" = "0",
  "GNRL_FAC_TYPE_CD" = "01",
  "CHOW_SW" = "",
  "CLIA_ID_NUMBER_1" = "",
  "CLIA_ID_NUMBER_2" = "",
  "CLIA_ID_NUMBER_3" = "",
  "CLIA_ID_NUMBER_4" = "",
  "CLIA_ID_NUMBER_5" = "",
  "COLCTN_STUS_SW" = "N",
  "RN_24_HR_WVR_SW" = "N",
  "RN_7_DAY_WVR_SW" = "",
  "BED_PER_ROOM_WVR_SW" = "",
  "LSC_WVR_SW" = "N",
  "ROOM_SIZE_WVR_SW" = "",
  "ENDSCPY_PRCDR_ROOMS_CNT" = "0",
  "ESRD_NTWRK_NUM" = "",
  "EXPRMT_RSRCH_CNDCTD_SW" = "",
  "FAX_PHNE_NUM" = "",
  "FY_END_MO_DAY_CD" = "0930",
  "FQHC_APPROVED_RHC_PROVIDER_NUM" = "",
  "FED_FUNDD_FQHC_SW" = "",
  "HHA_QLFYD_OPT_SPCH_SW" = "",
  "HH_AIDE_TRNG_PGM_CD" = "",
  "HOME_TRNG_SPRT_ONLY_SRVC_SW" = "",
  "MDCR_HOSPC_SW" = "",
  "HOSP_BSD_SW" = "",
  "INCNTR_NCTRNL_SRVC_SW" = "",
  "LTC_CROSS_REF_PROVIDER_NUMBER" = "",
  "MDCL_SCHL_AFLTN_CD" = "4",
  "MEDICARE_HOSPICE_PROVIDER_NUM" = "",
  "MDCD_MDCR_PRTCPTG_PRVDR_SW" = "Y",
  "MEDICARE_MEDICAID_PRVDR_NUMBER" = "",
  "MLT_FAC_ORG_NAME" = "",
  "MLT_OWND_FAC_ORG_SW" = "",
  "NCRY_PRVDR_DSGNTD_DT" = "",
  "NCRY_PRVDR_DSGNTD_AS_SW" = "N",
  "NCRY_PRVDR_LOST_DT" = "",
  "MEET_1861_SW" = "N",
  "NPP_TYPE_CD" = "",
  "TOT_OFSITE_CNCR_HOSP_CNT" = "0",
  "TOT_OFSITE_CHLDRN_HOSP_CNT" = "0",
  "TOT_OFSITE_EMER_DEPT_CNT" = "0",
  "TOT_OFSITE_INPTNT_LCTN_CNT" = "0",
  "TOT_OFSITE_LTC_HOSP_CNT" = "0",
  "TOT_OFSITE_OPTHLMC_SRGRY_CNT" = "0",
  "TOT_OFSITE_OTHR_LCTN_CNT" = "2",
  "TOT_OFSITE_PSYCH_HOSP_CNT" = "0",
  "TOT_OFSITE_PSYCH_UNIT_CNT" = "0",
  "TOT_OFSITE_REHAB_HOSP_CNT" = "0",
  "TOT_OFSITE_REHAB_UNIT_CNT" = "0",
  "TOT_OFSITE_URGNT_CARE_CNTR_CNT" = "0",
  "OFSITE_LCTN_CNT" = "2",
  "OPRTG_ROOM_CNT" = "0",
  "ORGNZ_FMLY_MBR_GRP_SW" = "",
  "ORGNZ_RSDNT_GRP_SW" = "",
  "PARENT_PROVIDER_NUMBER" = "",
  "FQHC_APRVD_RHC_SW" = "",
  "MDCR_PRTCPTN_OP_PT_SPCH_SW" = "",
  "PGM_PRTCPTN_CD" = "3",
  "PRVDR_BSD_FAC_SW" = "",
  "PRVNC_CD" = "",
  "PSYCH_UNIT_BED_CNT" = "0",
  "PSYCH_UNIT_EFCTV_DT" = "",
  "PSYCH_UNIT_SW" = "N",
  "PSYCH_UNIT_TRMNTN_CD" = "",
  "PSYCH_UNIT_TRMNTN_DT" = "",
  "REHAB_UNIT_BED_CNT" = "0",
  "REHAB_UNIT_EFCTV_DT" = "",
  "REHAB_UNIT_SW" = "N",
  "REHAB_UNIT_TRMNTN_CD" = "",
  "REHAB_UNIT_TRMNTN_DT" = "",
  "RELATED_PROVIDER_NUMBER" = "",
  "ACUTE_RNL_DLYS_SRVC_CD" = "0",
  "PSYCH_SRVC_CD" = "1",
  "HH_AIDE_SRVC_CD" = "",
  "ALCHL_DRUG_SRVC_CD" = "0",
  "ANSTHSA_SRVC_CD" = "3",
  "APLNC_EQUIP_SRVC_CD" = "",
  "AUDLGY_SRVC_CD" = "0",
  "BLOOD_SRVC_OFSITE_RSDNT_SW" = "",
  "BLOOD_SRVC_ONST_NRSDNT_SW" = "",
  "BLOOD_SRVC_ONST_RSDNT_SW" = "",
  "BURN_CARE_UNIT_SRVC_CD" = "0",
  "CRDC_CTHRTZTN_LAB_SRVC_CD" = "1",
  "OPEN_HRT_SRGRY_SRVC_CD" = "0",
  "CARF_IP_REHAB_SRVC_CD" = "0",
  "CHMTHRPY_SRVC_CD" = "3",
  "CHRPRCTIC_SRVC_CD" = "0",
  "CL_SRVC_OFSITE_RSDNT_SW" = "",
  "CL_SRVC_ONST_NRSDNT_SW" = "",
  "CL_SRVC_ONST_RSDNT_SW" = "",
  "CL_SRVC_CD" = "3",
  "CRNRY_CARE_UNIT_SRVC_CD" = "0",
  "CNSLNG_SRVC_CD" = "",
  "CT_SCAN_SRVC_CD" = "1",
  "DNTL_SRVC_CD" = "0",
  "DNTL_SRVC_OFSITE_RSDNT_SW" = "",
  "DNTL_SRVC_ONST_NRSDNT_SW" = "",
  "DNTL_SRVC_ONST_RSDNT_SW" = "",
  "SHCK_TRMA_SRVC_CD" = "0",
  "DGNSTC_RDLGY_SRVC_CD" = "1",
  "DTRY_SRVC_CD" = "1",
  "DTRY_OFSITE_RSDNT_SW" = "",
  "DTRY_ONST_NRSDNT_SW" = "",
  "DTRY_ONST_RSDNT_SW" = "",
  "DCTD_ER_SRVC_CD" = "1",
  "EMER_PSYCH_SRVC_CD" = "1",
  "XTRCRPRL_SHCK_LTHTRPTR_SRVC_CD" = "0",
  "FRNSC_PSYCH_SRVC_CD" = "0",
  "GRTRC_PSYCH_SRVC_CD" = "0",
  "GRNTLGCL_SPCLTY_SRVC_CD" = "0",
  "SP_HOME_TRNG_SPRT_HD_SW" = "",
  "HMDLYS_SRVC_SW" = "",
  "HMMKR_SRVC_CD" = "",
  "HSEKPNG_SRVC_OFSITE_RSDNT_SW" = "",
  "HSEKPNG_SRVC_ONST_NRSDNT_SW" = "",
  "HSEKPNG_SRVC_ONST_RSDNT_SW" = "",
  "IP_SRGCL_SRVC_CD" = "1",
  "INTRN_RSDNT_SRVC_CD" = "",
  "MDCL_SCL_SRVC_CD" = "",
  "MDCL_SUPLY_SRVC_CD" = "",
  "ICU_SRVC_CD" = "1",
  "MDCR_TRNSPLNT_CNTR_SRVC_CD" = "0",
  "MENTL_HLTH_OFSITE_RSDNT_SW" = "",
  "MENTL_HLTH_ONST_NRSDNT_SW" = "",
  "MENTL_HLTH_ONST_RSDNT_SW" = "",
  "MGNTC_RSNC_IMG_SRVC_CD" = "1",
  "NEONTL_ICU_SRVC_CD" = "0",
  "NEONTL_NRSRY_SRVC_CD" = "0",
  "NRSRGCL_SRVC_CD" = "0",
  "ORGN_TRNSPLNT_SRVC_CD" = "0",
  "NUCLR_MDCN_SRVC_CD" = "1",
  "NRSNG_SRVC_EMPLEE_SW" = "",
  "NRSNG_SRVC_CNTRCTR_SW" = "",
  "NRSNG_SRVC_ARNGMT_SW" = "",
  "NRSNG_SRVC_CD" = "",
  "NRSNG_SRVC_OFSITE_RSDNT_SW" = "",
  "NRSNG_SRVC_ONST_NRSDNT_SW" = "",
  "NRSNG_SRVC_ONST_RSDNT_SW" = "",
  "NTRTNL_GDNC_SRVC_CD" = "",
  "OB_SRVC_CD" = "1",
  "OPTHLMC_SRGY_SRVC_CD" = "1",
  "OPTMTRC_SRVC_CD" = "0",
  "OPRTG_ROOM_SRVC_CD" = "1",
  "ORTHPDC_SRGY_SRVC_CD" = "1",
  "ORTHTC_PRSTHTC_EMPLEE_SW" = "",
  "ORTHTC_PRSTHTC_CNTRCTR_SW" = "",
  "ORTHTC_PRSTHTC_ARNGMT_SW" = "",
  "OT_EMPLEE_SW" = "",
  "OT_CNTRCTR_SW" = "",
  "OT_ARNGMT_SW" = "",
  "OT_SRVC_CD" = "0",
  "OT_SRVC_OFSITE_RSDNT_SW" = "",
  "OT_SRVC_ONST_NRSDNT_SW" = "",
  "OT_SRVC_ONST_RSDNT_SW" = "",
  "OTHR_SRVC_CD" = "",
  "OP_SRVC_CD" = "1",
  "OP_PSYCH_SRVC_CD" = "0",
  "OP_REHAB_SRVC_CD" = "0",
  "OP_SRGRY_UNIT_SRVC_CD" = "1",
  "PED_SRVC_CD" = "1",
  "PED_ICU_SRVC_CD" = "0",
  "SP_HOME_TRNG_SPRT_PD_SW" = "",
  "PRTNL_DLYS_SRVC_SW" = "",
  "PET_SCAN_SRVC_CD" = "1",
  "PHRMCY_SRVC_OFSITE_RSDNT_SW" = "",
  "PHRMCY_SRVC_ONST_NRSDNT_SW" = "",
  "PHRMCY_SRVC_ONST_RSDNT_SW" = "",
  "PHYSN_EMPLEE_SW" = "",
  "PHYSN_CNTRCTR_SW" = "",
  "PHYSN_ARNGMT_SW" = "",
  "PHYSN_SRVC_CD" = "",
  "PHYSN_EXT_SRVC_OFSITE_RSDNT_SW" = "",
  "PHYSN_EXT_SRVC_ONST_NRSDNT_SW" = "",
  "PHYSN_EXT_SRVC_ONST_RSDNT_SW" = "",
  "PHYSN_SRVC_OFSITE_RSDNT_SW" = "",
  "PHYSN_SRVC_ONST_NRSDNT_SW" = "",
  "PHYSN_SRVC_ONST_RSDNT_SW" = "",
  "PDTRY_SRVC_OFSITE_RSDNT_SW" = "",
  "PDTRY_SRVC_ONST_NRSDNT_SW" = "",
  "PDTRY_SRVC_ONST_RSDNT_SW" = "",
  "PSTOPRTV_RCVRY_SRVC_CD" = "1",
  "CHLD_ADLSCNT_PSYCH_SRVC_CD" = "1",
  "PSYCHLGCL_EMPLEE_SW" = "",
  "PSYCHLGCL_CNTRCTR_SW" = "",
  "PSYCHLGCL_ARNGMT_SW" = "",
  "PT_EMPLEE_SW" = "",
  "PT_CNTRCTR_SW" = "",
  "PT_ARNGMT_SW" = "",
  "PT_SRVC_CD" = "3",
  "PT_OFSITE_RSDNT_SW" = "",
  "PT_ONST_NRSDNT_SW" = "",
  "PT_ONST_RSDNT_SW" = "",
  "RCNSTRCTN_SRGY_SRVC_CD" = "0",
  "RSPRTRY_CARE_EMPLEE_SW" = "",
  "RSPRTRY_CARE_CNTRCTR_SW" = "",
  "RSPRTRY_CARE_ARNGMT_SW" = "",
  "RSPRTRY_CARE_SRVC_CD" = "1",
  "SHRT_TERM_IP_SRVC_CD" = "",
  "SCL_EMPLEE_SW" = "",
  "SCL_CNTRCTR_SW" = "",
  "SCL_ARNGMT_SW" = "",
  "SCL_SRVC_CD" = "1",
  "SCL_WORK_SRVC_OFSITE_RSDNT_SW" = "",
  "SCL_WORK_SRVC_ONST_NRSDNT_SW" = "",
  "SCL_WORK_SRVC_ONST_RSDNT_SW" = "",
  "SPCH_PTHLGY_EMPLEE_SW" = "",
  "SPCH_PTHLGY_CNTRCTR_SW" = "",
  "SPCH_PTHLGY_ARNGMT_SW" = "",
  "SPCH_PTHLGY_SRVC_CD" = "1",
  "SPCH_PTHLGY_OFSITE_RSDNT_SW" = "",
  "SPCH_PTHLGY_ONST_NRSDNT_SW" = "",
  "SPCH_PTHLGY_ONST_RSDNT_SW" = "",
  "SPCH_THRPY_SRVC_CD" = "",
  "SRGCL_ICU_SRVC_CD" = "0",
  "ACTVTY_OTHR_OFSITE_RSDNT_SW" = "",
  "ACTVTY_OTHR_ONST_NRSDNT_SW" = "",
  "ACTVTY_OTHR_ONST_RSDNT_SW" = "",
  "SCL_SRVC_OTHR_OFSITE_RSDNT_SW" = "",
  "SCL_SRVC_OTHR_ONST_NRSDNT_SW" = "",
  "SCL_SRVC_OTHR_ONST_RSDNT_SW" = "",
  "ACTVTY_OFSITE_RSDNT_SW" = "",
  "ACTVTY_ONST_NRSDNT_SW" = "",
  "ACTVTY_ONST_RSDNT_SW" = "",
  "THRPTC_RDLGY_SRVC_CD" = "1",
  "THRPTC_RCRTNL_OFSITE_RSDNT_SW" = "",
  "THRPTC_RCRTNL_ONST_NRSDNT_SW" = "",
  "THRPTC_RCRTNL_ONST_RSDNT_SW" = "",
  "URGNT_CARE_SRVC_CD" = "0",
  "VCTNL_GDNC_SRVC_CD" = "",
  "VCTNL_SRVC_OFSITE_RSDNT_SW" = "",
  "VCTNL_SRVC_ONST_NRSDNT_SW" = "",
  "VCTNL_SRVC_ONST_RSDNT_SW" = "",
  "DGNSTC_XRAY_OFSITE_RSDNT_SW" = "",
  "DGNSTC_XRAY_ONST_NRSDNT_SW" = "",
  "DGNSTC_XRAY_ONST_RSDNT_SW" = "",
  "ACUTE_RESP_CARE_CD" = "",
  "OVRRD_STFG_SW" = "N",
  "PROFNL_ADMIN_CNTRCT_CNT" = "",
  "PROFNL_ADMIN_FLTM_CNT" = "",
  "PROFNL_ADMIN_PRTM_CNT" = "",
  "HH_AIDE_EMPLEE_CNT" = "",
  "HH_AIDE_VLNTR_CNT" = "",
  "PRSNEL_OTHR_CNT" = "347.75",
  "NRS_AIDE_CNTRCT_CNT" = "",
  "NRS_AIDE_FLTM_CNT" = "",
  "NRS_AIDE_PRTM_CNT" = "",
  "CNSLR_EMPLEE_CNT" = "",
  "CNSLR_VLNTR_CNT" = "",
  "CRNA_CNT" = "6.5",
  "DNTST_CNTRCT_CNT" = "",
  "DNTST_FLTM_CNT" = "",
  "DNTST_PRTM_CNT" = "",
  "DIETN_CNT" = "1",
  "DIETN_CNTRCT_CNT" = "",
  "DIETN_FLTM_CNT" = "",
  "DIETN_PRTM_CNT" = "",
  "DRCT_CARE_PRSNEL_CNT" = "",
  "FOOD_SRVC_CNTRCT_CNT" = "",
  "FOOD_SRVC_FLTM_CNT" = "",
  "FOOD_SRVC_PRTM_CNT" = "",
  "HH_AIDE_CNT" = "",
  "HMMKR_EMPLEE_CNT" = "",
  "HMMKR_VLNTR_CNT" = "",
  "HSEKPNG_CNTRCT_CNT" = "",
  "HSEKPNG_FLTM_CNT" = "",
  "HSEKPNG_PRTM_CNT" = "",
  "LAB_TCHNCN_CNT" = "0",
  "LPN_CNT" = "",
  "LPN_LVN_CNT" = "19.5",
  "LPN_LVN_CNTRCT_CNT" = "",
  "LPN_LVN_FLTM_CNT" = "",
  "LPN_LVN_PRTM_CNT" = "",
  "LPN_LVN_VLNTR_CNT" = "",
  "MDCL_DRCTR_CNTRCT_CNT" = "",
  "MDCL_DRCTR_FLTM_CNT" = "",
  "MDCL_DRCTR_PRTM_CNT" = "",
  "MDCL_SCL_WORKR_CNT" = "2.5",
  "MDCL_SCL_WORKR_VLNTR_CNT" = "",
  "MDCL_TCHNLGST_CNT" = "0",
  "MDCTN_AIDE_CNTRCT_CNT" = "",
  "MDCTN_AIDE_FLTM_CNT" = "",
  "MDCTN_AIDE_PRTM_CNT" = "",
  "MENTL_HLTH_SRVC_CNTRCT_CNT" = "",
  "MENTL_HLTH_SRVC_FLTM_CNT" = "",
  "MENTL_HLTH_SRVC_PRTM_CNT" = "",
  "NUCLR_MDCN_TCHNCN_CNT" = "0",
  "NAT_CNTRCT_CNT" = "",
  "NAT_FLTM_CNT" = "",
  "NAT_PRTM_CNT" = "",
  "NRS_PRCTNR_CNT" = "0",
  "NRS_ADMINV_CNTRCT_CNT" = "",
  "NRS_ADMINV_FLTM_CNT" = "",
  "NRS_ADMINV_PRTM_CNT" = "",
  "OCPTNL_THRPST_CNT" = "0",
  "OCPTNL_THRPST_CNTRCT_CNT" = "",
  "OCPTNL_THRPST_FLTM_CNT" = "",
  "OCPTNL_THRPST_PRTM_CNT" = "",
  "OT_AIDE_CNTRCT_CNT" = "",
  "OT_AIDE_FLTM_CNT" = "",
  "OT_AIDE_PRTM_CNT" = "",
  "OT_ASTNT_CNTRCT_CNT" = "",
  "OT_ASTNT_FLTM_CNT" = "",
  "OT_ASTNT_PRTM_CNT" = "",
  "VLNTR_OTHR_CNT" = "",
  "ACTVTY_STF_OTHR_CNTRCT_CNT" = "",
  "ACTVTY_STF_OTHR_FLTM_CNT" = "",
  "ACTVTY_STF_OTHR_PRTM_CNT" = "",
  "PHYSN_OTHR_CNTRCT_CNT" = "",
  "PHYSN_OTHR_FLTM_CNT" = "",
  "PHYSN_OTHR_PRTM_CNT" = "",
  "SCL_SRVC_OTHR_STF_CNTRCT_CNT" = "",
  "SCL_SRVC_OTHR_STF_FLTM_CNT" = "",
  "SCL_SRVC_OTHR_STF_PRTM_CNT" = "",
  "STF_OTHR_CNTRCT_CNT" = "",
  "STF_OTHR_FLTM_CNT" = "",
  "STF_OTHR_PRTM_CNT" = "",
  "PHRMCST_CNTRCT_CNT" = "",
  "PHRMCST_FLTM_CNT" = "",
  "PHRMCST_PRTM_CNT" = "",
  "PHYS_THRPST_CNTRCT_CNT" = "",
  "PHYS_THRPST_FLTM_CNT" = "",
  "PHYS_THRPST_PRTM_CNT" = "",
  "PHYSN_CNT" = "1",
  "PHYSN_VLNTR_CNT" = "",
  "PHYSN_ASTNT_CNT" = "0",
  "PHYSN_EXT_CNTRCT_CNT" = "",
  "PHYSN_EXT_FLTM_CNT" = "",
  "PHYSN_EXT_PRTM_CNT" = "",
  "RSDNT_PHYSN_CNT" = "0",
  "PDTRST_CNTRCT_CNT" = "",
  "PDTRST_FLTM_CNT" = "",
  "PDTRST_PRTM_CNT" = "",
  "PSYCHLGST_CNT" = "0",
  "PHYS_THRPST_STF_CNT" = "",
  "PHYS_THRPST_CNT" = "0",
  "PHYS_THRPST_ARNGMT_CNT" = "",
  "PT_AIDE_CNTRCT_CNT" = "",
  "PT_AIDE_FLTM_CNT" = "",
  "PT_AIDE_PRTM_CNT" = "",
  "PT_ASTNT_CNTRCT_CNT" = "",
  "PT_ASTNT_FLTM_CNT" = "",
  "PT_ASTNT_PRTM_CNT" = "",
  "ACTVTY_PROFNL_CNTRCT_CNT" = "",
  "ACTVTY_PROFNL_FLTM_CNT" = "",
  "ACTVTY_PROFNL_PRTM_CNT" = "",
  "RDLGY_TCHNCN_CNT" = "0",
  "REG_PHRMCST_CNT" = "4.75",
  "INHLTN_THRPST_CNT" = "12",
  "RN_CNT" = "137",
  "RN_CNTRCT_CNT" = "",
  "RN_FLTM_CNT" = "",
  "RN_PRTM_CNT" = "",
  "RN_VLNTR_CNT" = "",
  "RN_DRCTR_CNTRCT_CNT" = "",
  "RN_DRCTR_FLTM_CNT" = "",
  "RN_DRCTR_PRTM_CNT" = "",
  "SCL_WORKR_CNT" = "",
  "SCL_WORKR_CNTRCT_CNT" = "",
  "SCL_WORKR_FLTM_CNT" = "",
  "SCL_WORKR_PRTM_CNT" = "",
  "SPCH_PTHLGST_ARNGMT_CNT" = "",
  "SPCH_PTHLGST_CNTRCT_CNT" = "",
  "SPCH_PTHLGST_FLTM_CNT" = "",
  "SPCH_PTHLGST_PRTM_CNT" = "",
  "SPCH_PTHLGST_CNT" = "",
  "SPCH_PTHLGST_AUDLGST_CNT" = "0",
  "TCHNCL_STF_NUM" = "",
  "TCHNCN_CNT" = "",
  "THRPTC_RCRTNL_CNTRCT_CNT" = "",
  "THRPTC_RCRTNL_FLTM_CNT" = "",
  "THRPTC_RCRTNL_PRTM_CNT" = "",
  "EMPLEE_CNT" = "",
  "VLNTR_CNT" = "",
  "SBUNIT_CNT" = "",
  "SBUNIT_SW" = "",
  "SBUNIT_OPRTN_SW" = "",
  "DNTL_SRGRY_SW" = "",
  "OTLRYNGLGY_SRGRY_SW" = "",
  "ENDSCPY_SRGRY_SW" = "",
  "OB_GYN_SRGRY_SW" = "",
  "OPTHMLGY_SRGRY_SW" = "",
  "ORTHPDC_SRGRY_SW" = "",
  "OTHR_SRGRY_SW" = "",
  "PAIN_SRGRY_SW" = "",
  "PLSTC_SRGRY_SW" = "",
  "FT_SRGRY_SW" = "",
  "SB_SW" = "N",
  "SB_SIZE_CD" = "",
  "TCHNLGST_2_YR_RDLGC_CNT" = "",
  "TCHNLGST_ASCT_DGR_CNT" = "",
  "TCHNLGST_BS_BA_DGR_CNT" = "",
  "DLYS_STN_CNT" = ""
)
