url <- URL_CMS_List("utilization")

length(url)

x <- provider:::base_request(paste0(url[12], "?size=10&offset=0")) |>
  collapse::qTBL()

x |> str()

colnames(x) |> create_vec()

c(
  Rndrng_NPI = "npi",
  Rndrng_Prvdr_Last_Org_Name = "last",
  Rndrng_Prvdr_First_Name = "first",
  Rndrng_Prvdr_Crdntls = "cred",
  Rndrng_Prvdr_Ent_Cd = "entity",
  Rndrng_Prvdr_St1 = "address",
  Rndrng_Prvdr_St2 = "add_2",
  Rndrng_Prvdr_City = "city",
  Rndrng_Prvdr_State_Abrvtn = "state",
  Rndrng_Prvdr_Zip5 = "zip",
  Rndrng_Prvdr_Type = "specialty",
  Rndrng_Prvdr_Mdcr_Prtcptg_Ind = "part_ind",
  Tot_HCPCS_Cds = "hcpcs",
  Tot_Benes = "patients",
  Tot_Srvcs = "services",
  Tot_Sbmtd_Chrg = "charges",
  Tot_Mdcr_Alowd_Amt = "allowed",
  Tot_Mdcr_Pymt_Amt = "payment",
  Tot_Mdcr_Stdzd_Amt = "standard",
  Bene_Avg_Age = "bene_age",
  Bene_Feml_Cnt = "bene_female",
  Bene_Male_Cnt = "bene_male",
  Bene_Dual_Cnt = "bene_dual",
  Bene_Ndual_Cnt = "bene_ndual",
  Bene_Avg_Risk_Scre = "bene_risk_score"
  # Rndrng_Prvdr_MI = "Rndrng_Prvdr_MI",
  # Rndrng_Prvdr_State_FIPS = "Rndrng_Prvdr_State_FIPS",
  # Rndrng_Prvdr_RUCA = "Rndrng_Prvdr_RUCA",
  # Rndrng_Prvdr_RUCA_Desc = "Rndrng_Prvdr_RUCA_Desc",
  # Rndrng_Prvdr_Cntry = "Rndrng_Prvdr_Cntry",
  # Drug_Sprsn_Ind = "Drug_Sprsn_Ind",
  # Drug_Tot_HCPCS_Cds = "Drug_Tot_HCPCS_Cds",
  # Drug_Tot_Benes = "Drug_Tot_Benes",
  # Drug_Tot_Srvcs = "Drug_Tot_Srvcs",
  # Drug_Sbmtd_Chrg = "Drug_Sbmtd_Chrg",
  # Drug_Mdcr_Alowd_Amt = "Drug_Mdcr_Alowd_Amt",
  # Drug_Mdcr_Pymt_Amt = "Drug_Mdcr_Pymt_Amt",
  # Drug_Mdcr_Stdzd_Amt = "Drug_Mdcr_Stdzd_Amt",
  # Med_Sprsn_Ind = "Med_Sprsn_Ind",
  # Med_Tot_HCPCS_Cds = "Med_Tot_HCPCS_Cds",
  # Med_Tot_Benes = "Med_Tot_Benes",
  # Med_Tot_Srvcs = "Med_Tot_Srvcs",
  # Med_Sbmtd_Chrg = "Med_Sbmtd_Chrg",
  # Med_Mdcr_Alowd_Amt = "Med_Mdcr_Alowd_Amt",
  # Med_Mdcr_Pymt_Amt = "Med_Mdcr_Pymt_Amt",
  # Med_Mdcr_Stdzd_Amt = "Med_Mdcr_Stdzd_Amt",
  # Bene_Age_LT_65_Cnt = "Bene_Age_LT_65_Cnt",
  # Bene_Age_65_74_Cnt = "Bene_Age_65_74_Cnt",
  # Bene_Age_75_84_Cnt = "Bene_Age_75_84_Cnt",
  # Bene_Age_GT_84_Cnt = "Bene_Age_GT_84_Cnt",
  # Bene_Race_Wht_Cnt = "Bene_Race_Wht_Cnt",
  # Bene_Race_Black_Cnt = "Bene_Race_Black_Cnt",
  # Bene_Race_API_Cnt = "Bene_Race_API_Cnt",
  # Bene_Race_Hspnc_Cnt = "Bene_Race_Hspnc_Cnt",
  # Bene_Race_NatInd_Cnt = "Bene_Race_NatInd_Cnt",
  # Bene_Race_Othr_Cnt = "Bene_Race_Othr_Cnt",
  # Bene_CC_BH_ADHD_OthCD_V1_Pct = "Bene_CC_BH_ADHD_OthCD_V1_Pct",
  # Bene_CC_BH_Alcohol_Drug_V1_Pct = "Bene_CC_BH_Alcohol_Drug_V1_Pct",
  # Bene_CC_BH_Tobacco_V1_Pct = "Bene_CC_BH_Tobacco_V1_Pct",
  # Bene_CC_BH_Alz_NonAlzdem_V2_Pct = "Bene_CC_BH_Alz_NonAlzdem_V2_Pct",
  # Bene_CC_BH_Anxiety_V1_Pct = "Bene_CC_BH_Anxiety_V1_Pct",
  # Bene_CC_BH_Bipolar_V1_Pct = "Bene_CC_BH_Bipolar_V1_Pct",
  # Bene_CC_BH_Mood_V2_Pct = "Bene_CC_BH_Mood_V2_Pct",
  # Bene_CC_BH_Depress_V1_Pct = "Bene_CC_BH_Depress_V1_Pct",
  # Bene_CC_BH_PD_V1_Pct = "Bene_CC_BH_PD_V1_Pct",
  # Bene_CC_BH_PTSD_V1_Pct = "Bene_CC_BH_PTSD_V1_Pct",
  # Bene_CC_BH_Schizo_OthPsy_V1_Pct = "Bene_CC_BH_Schizo_OthPsy_V1_Pct",
  # Bene_CC_PH_Asthma_V2_Pct = "Bene_CC_PH_Asthma_V2_Pct",
  # Bene_CC_PH_Afib_V2_Pct = "Bene_CC_PH_Afib_V2_Pct",
  # Bene_CC_PH_Cancer6_V2_Pct = "Bene_CC_PH_Cancer6_V2_Pct",
  # Bene_CC_PH_CKD_V2_Pct = "Bene_CC_PH_CKD_V2_Pct",
  # Bene_CC_PH_COPD_V2_Pct = "Bene_CC_PH_COPD_V2_Pct",
  # Bene_CC_PH_Diabetes_V2_Pct = "Bene_CC_PH_Diabetes_V2_Pct",
  # Bene_CC_PH_HF_NonIHD_V2_Pct = "Bene_CC_PH_HF_NonIHD_V2_Pct",
  # Bene_CC_PH_Hyperlipidemia_V2_Pct = "Bene_CC_PH_Hyperlipidemia_V2_Pct",
  # Bene_CC_PH_Hypertension_V2_Pct = "Bene_CC_PH_Hypertension_V2_Pct",
  # Bene_CC_PH_IschemicHeart_V2_Pct = "Bene_CC_PH_IschemicHeart_V2_Pct",
  # Bene_CC_PH_Osteoporosis_V2_Pct = "Bene_CC_PH_Osteoporosis_V2_Pct",
  # Bene_CC_PH_Parkinson_V2_Pct = "Bene_CC_PH_Parkinson_V2_Pct",
  # Bene_CC_PH_Arthritis_V2_Pct = "Bene_CC_PH_Arthritis_V2_Pct",
  # Bene_CC_PH_Stroke_TIA_V2_Pct = "Bene_CC_PH_Stroke_TIA_V2_Pct",
)
