---
title: "Overview of Provider"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Overview of Provider}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse  = TRUE,
  echo      = TRUE, 
  message   = FALSE, 
  warning   = FALSE,
  error     = TRUE,
  comment   = "#>",
  dpi       = 300, 
  out.width = "100%",
  fig.path  = "man/figures/README-"
)
```

```{r}
library(provider)
```

<br>

## Starting with the NPPES Registry

```r
nppes_npi(npi = 1043477615)
```

<details><summary>Code</summary>

```{r}
nppes <- nppes_npi(npi = 1043477615)

nppes_basic <- nppes |> 
  dplyr::select(npi:years_passed, 
                status,
                sole_proprietor,
                gender) |> 
  dplyr::slice_head() |> 
  dplyr::mutate(status = dplyr::if_else(status == "A", "Active", status),
                gender = dplyr::if_else(gender == "F", "Female", "Male")) |> 
  provider:::gt_prov(source = gt::md("Source: [NPPES NPI Registry](https://npiregistry.cms.hhs.gov/api-page)"), 
                     checkmark = c("sole_proprietor"),
                     title = gt::md("NPPES **Basic Information**"),
                     subtitle = glue::glue("Provider: {first} {middle}. {last}, {cred}.", 
                                           first = nppes$first_name[[1]], 
                                           middle = nppes$middle_name[[1]],
                                           last = nppes$last_name[[1]],
                                           cred = nppes$credential[[1]])) |> 
  gt::cols_label(entype = "Type", 
                 enumeration_date = "Date",
                 years_passed = "Years") |> 
  gt::tab_spanner(label = "ENUMERATION", 
                  columns = c(enumeration_date, 
                              years_passed,
                              status))

nppes_location <- nppes |> 
  dplyr::select(purpose,
                street:zipcode,
                phone_number) |> 
  dplyr::distinct_all() |> 
  dplyr::mutate(zipcode = campfin::normal_zip(zipcode),
                state = campfin::expand_state(state),
                phone_number = campfin::normal_phone(phone_number)) |> 
  provider:::gt_prov(source = gt::md("Source: [NPPES NPI Registry](https://npiregistry.cms.hhs.gov/api-page)"), 
                     divider = c("purpose"),
                     title = gt::md("NPPES **Location Information**"),
                     subtitle = glue::glue("Provider: {first} {middle}. {last}, {cred}.", 
                                           first = nppes$first_name[[1]], 
                                           middle = nppes$middle_name[[1]],
                                           last = nppes$last_name[[1]],
                                           cred = nppes$credential[[1]])) |> 
  gt::cols_label(zipcode = "Zip Code")

nppes_taxonomy <- nppes |> 
  dplyr::select(tx_code, 
                tx_primary, 
                tx_desc, 
                tx_state, 
                tx_license) |> 
  dplyr::distinct_all() |> 
  provider:::gt_prov(source = gt::md("Source: [NPPES NPI Registry](https://npiregistry.cms.hhs.gov/api-page)"), 
                     checkmark = c("tx_primary"),
                     title = gt::md("NPPES **Taxonomy Information**"),
                     subtitle = glue::glue("Provider: {first} {middle}. {last}, {cred}.", 
                                           first = nppes$first_name[[1]], 
                                           middle = nppes$middle_name[[1]],
                                           last = nppes$last_name[[1]],
                                           cred = nppes$credential[[1]])) |> 
  gt::cols_label(tx_code = "Taxonomy",
                 tx_desc = "Description",
                 tx_state = "State",
                 tx_license = "License",
                 tx_primary = "Primary") |> 
  gtExtras::gt_highlight_rows(
     rows = tx_primary == TRUE,
     fill = "#FAFAD2",
     bold_target_only = FALSE,
     target_col = tx_primary,
     font_color = "black",
     font_weight = "bold"
   )
```

</details>


```{r, echo=FALSE, eval=TRUE}
nppes_basic
```


```{r, echo=FALSE, eval=TRUE}
nppes_location
```

```{r, echo=FALSE, eval=TRUE}
nppes_taxonomy
```

<br>


```r
order_refer(npi = 1043477615)
```

<details><summary>Code</summary>

```{r}
oar <- order_refer(npi = 1043477615)

oar_gt <- oar |> 
  dplyr::select(
    "Medicare Part B" = partb, 
    "Home Health (HHA)" = hha, 
    "Durable Medical Equipment (DME)" = dme, 
    "Power Mobility Devices (PMD)" = pmd) |> 
  provider:::display_long() |> 
  dplyr::select(service = name, 
                eligible = value) |> 
  provider:::gt_prov(checkmark = c("eligible"),
                     title = "Medicare Order & Referring Eligibility",
                     subtitle = glue::glue("Provider: {first} {last}. NPI: {npi}.", 
                                           first = oar$first_name[[1]], 
                                           last = oar$last_name[[1]],
                                           npi = oar$npi[[1]]),
                     source = gt::md("Source: [Medicare Order and Referring API](https://data.cms.gov/provider-characteristics/medicare-provider-supplier-enrollment/order-and-referring)"))
```

</details>

```{r, echo=FALSE, eval=TRUE}
oar_gt
```

<br>

```r
provider_enrollment(npi = 1043477615)
```
<details><summary>Code</summary>

```{r}
pro <- provider_enrollment(npi = 1043477615)

pro_gt <- pro |> 
  dplyr::mutate(state = campfin::expand_state(state)) |> 
  dplyr::select("PECOS Associate Control (PAC) ID" = pac_id, 
                "Enrollment ID" = enroll_id, 
                "Specialty Code" = specialty_code, 
                "Specialty Description" = specialty_desc,
                State = state, 
                "Organization Name" = org_name) |> 
  provider:::display_long() |> 
  dplyr::select(item = name, 
                result = value) |> 
  provider:::gt_prov(title = "Medicare Provider Enrollment Information",
                     divider = c("item"),
                     source = gt::md("Source: [Medicare Fee-For-Service Public Provider Enrollment API](https://data.cms.gov/provider-characteristics/medicare-provider-supplier-enrollment/medicare-fee-for-service-public-provider-enrollment)"),
                     subtitle = glue::glue("Provider: {first} {middle}. {last}. NPI: {npi}", 
                                           first = pro$first_name[[1]], 
                                           middle = pro$middle_name[[1]],
                                           last = pro$last_name[[1]],
                                           npi = pro$npi[[1]]))
```

</details>

```{r, echo=FALSE, eval=TRUE}
pro_gt
```


<br>

## Doctors and Clinicians

```r
doctors_and_clinicians(npi = 1043477615)
```
<details><summary>Code</summary>

```{r}
drc <- doctors_and_clinicians(npi = 1043477615)

dcli_1 <- drc |> 
  dplyr::select(school, 
                grad_year, 
                grad_duration, 
                specialty, 
                ind_assn) |> 
  provider:::gt_prov(divider = c("grad_duration"),
                     qmark = c("ind_assn"),
    source = gt::md("Source: [Doctors and Clinicians National Downloadable File](https://data.cms.gov/provider-data/dataset/mj5m-pzi6)")) |> 
  gt::cols_label(school = "Medical School", 
                 grad_year = "Graduated", 
                 ind_assn = "Accepts Assignment")

dcli_2 <- drc |> 
  dplyr::select(org_name, 
                org_pac_id, 
                org_members, 
                address, 
                city, 
                state, 
                zipcode, 
                phone, 
                group_assn) |> 
  dplyr::mutate(zipcode = campfin::normal_zip(zipcode),
                phone = campfin::normal_phone(phone),
                state = campfin::expand_state(state)) |> 
  tidyr::unite("location", c(address, city, state, zipcode), sep = " ") |> 
  provider:::gt_prov(qmark = c("group_assn"),
    source = gt::md("Source: [Doctors and Clinicians National Downloadable File](https://data.cms.gov/provider-data/dataset/mj5m-pzi6)")) |> 
  gt::cols_label(org_name = "Organization Name", 
                 org_pac_id = "PAC ID", 
                 org_members = "No. of Members", 
                 group_assn = "Accepts Assignment")
```

</details>

```{r, echo=FALSE, eval=TRUE}
dcli_1
```


<br>

```{r, echo=FALSE, eval=TRUE}
dcli_2
```

<br>

## Facility Affiliations / Hospital Enrollment

```r
facility_affiliations(npi = 1043477615) |> 
  dplyr::pull(facility_ccn) |> 
  furrr::future_map(\(x) hospital_enrollment(facility_ccn = x)) |>
  purrr::list_rbind()
```
<details><summary>Code</summary>

```{r, message=TRUE}
fac <- facility_affiliations(npi = 1043477615)

hos <- fac |> 
  dplyr::pull(facility_ccn) |> 
  furrr::future_map(\(x) hospital_enrollment(facility_ccn = x)) |>
  purrr::list_rbind() |> 
  janitor::remove_empty(which = c("rows", "cols"))
```


```{r}
fac
hosp_1 <- fac_hosp |> 
  dplyr::select(
    org_name,
    npi, 
    pac_id_org,
    facility_ccn,
    enroll_id,
    specialty_desc,
    #specialty_code,
    multiple_npis) |> 
  provider:::gt_prov(checkmark = c("multiple_npis"),
    source = gt::md("Source: [CMS Hospital Enrollments](https://data.cms.gov/provider-characteristics/hospitals-and-other-facilities/hospital-enrollments)")) |> 
  gt::cols_label(org_name = "Organization Name",
                 pac_id_org = "PAC ID",
                 facility_ccn = "CCN",
                 enroll_id = "Enrollment ID",
                 #specialty_code = "Code",
                 specialty_desc = "Specialty",
                 multiple_npis = "Multiple NPIs")

hosp_2 <- fac_hosp |> 
  dplyr::select(
    org_name,
    incorp_date,
    incorp_duration,
    proprietary_nonprofit,
    address,
    city,
    state,
    zipcode) |> 
  dplyr::mutate(zipcode = campfin::normal_zip(zipcode),
                state = campfin::expand_state(state)) |> 
  tidyr::unite("location", c(address, city, state, zipcode), sep = " ") |> 
  provider:::gt_prov(divider = c("org_name"),
                     checkmark = c("proprietary_nonprofit"),
    source = gt::md("Source: [CMS Hospital Enrollments](https://data.cms.gov/provider-characteristics/hospitals-and-other-facilities/hospital-enrollments)")) |> 
  gt::cols_label(org_name = "Organization Name", 
                 incorp_date = "Date Incorporated",
                 incorp_duration = "Years Incorporated",
                 proprietary_nonprofit = "Nonprofit")

hosp_3 <- fac_hosp |> 
  dplyr::select(
    org_name,
    "General" = sg_general,
    "Acute Care" = sg_acute_care,
    "Alcohol/Drug" = sg_alcohol_drug,
    "Childrens" = sg_childrens,
    "Long-Term" = sg_long_term,
    "Short-Term" = sg_short_term,
    "Psychiatric" = sg_psychiatric,
    "Psych Unit" = sg_psychiatric_unit,
    "Rehabilitation" = sg_rehabilitation,
    "Rehab Unit" = sg_rehabilitation_unit,
    "Swing Bed Approved" = sg_swing_bed_approved,
    "Specialty Hospital" = sg_specialty_hospital,
    "Other" = sg_other) |> 
  tidyr::pivot_longer(cols = !org_name, 
                      names_to = "subgroup", 
                      values_to = "value") |> 
  tidyr::pivot_wider(names_from = org_name, 
                     values_from = value) |> 
  provider:::gt_prov(divider = c("subgroup"),
                     checkmark = c("THE CHAMBERSBURG HOSPITAL",
                                   "UPMC PINNACLE HOSPITALS"),
    source = gt::md("Source: [CMS Hospital Enrollments](https://data.cms.gov/provider-characteristics/hospitals-and-other-facilities/hospital-enrollments)"))
```

</details>

```{r, echo=FALSE, eval=TRUE}
hosp_1
```


<br>

```{r, echo=FALSE, eval=TRUE}
hosp_2
```

<br>

```{r, echo=FALSE, eval=TRUE}
hosp_3
```

<br>

## Revalidation Date / Reassignment

```r
revalidation_date(npi = 1043477615)
revalidation_reassign(npi = 1043477615)
```

<details><summary>Code</summary>

```{r}
re_date <- revalidation_date(npi = 1043477615) |> 
  dplyr::select(enroll_id, 
                enroll_state, 
                enroll_type, 
                enroll_specialty) |> 
  dplyr::mutate(enroll_state = campfin::expand_state(enroll_state)) |> 
  provider:::gt_prov(source = gt::md("Source: [Medicare Revalidation Due Date API](https://data.cms.gov/provider-characteristics/medicare-provider-supplier-enrollment/revalidation-due-date-list)")) |> 
  gt::cols_label(enroll_id = "Enrollment ID", 
                enroll_state = "Enrollment State", 
                enroll_type = "Enrollment Type", 
                enroll_specialty = "Enrollment Specialty")

re_assign <- revalidation_reassign(npi = 1043477615) |> 
  dplyr::select(business_name, 
                state_group, 
                pac_id_group, 
                enroll_id_group, 
                group_reassign_and_phys_assist) |> 
  dplyr::mutate(state_group = campfin::expand_state(state_group)) |> 
  provider:::gt_prov(source = gt::md("Source: [Medicare Revalidation Reassignment API](https://data.cms.gov/provider-characteristics/medicare-provider-supplier-enrollment/revalidation-reassignment-list)")) |> 
  gt::cols_label(business_name = "Business Name", 
                 state_group = "State", 
                 group_reassign_and_phys_assist = "Reassignments / Physicians Assistants",
                 pac_id_group = "PAC ID", 
                 enroll_id_group = "Enrollment ID")
```

</details>


```{r, echo=FALSE, eval=TRUE}
re_date
```

<br>

```{r, echo=FALSE, eval=TRUE}
re_assign
```

<br>

## Physician & Other Practitioners

```r
2014:2021 |> 
  furrr::future_map(\(x) physician_by_provider(year = x, npi = 1043477615)) |> 
  purrr::list_rbind()
```
<details><summary>Code</summary>

```{r}
provider <- 2014:2021 |> 
  furrr::future_map(\(x) physician_by_provider(year = x, npi = 1043477615)) |> 
  purrr::list_rbind()

provider_1 <- provider |> 
  dplyr::select(year, 
                tot_benes, 
                tot_srvcs,
                tot_charges,
                tot_allowed,
                tot_payment) |> 
  provider:::change_abs(tot_benes, year) |> 
  provider:::change_pct(tot_benes, tot_benes_chg, year) |> 
  provider:::change_abs(tot_srvcs, year) |> 
  provider:::change_pct(tot_srvcs, tot_srvcs_chg, year) |> 
  dplyr::select(!c(tot_benes_chg, tot_srvcs_chg)) |> 
  provider:::gt_prov(source = gt::md("Source: [Medicare Physician & Other Practitioners: by Provider
                                     API](https://data.cms.gov/provider-summary-by-type-of-service/medicare-physician-other-practitioners/medicare-physician-other-practitioners-by-provider)"),
                     title = gt::md("Medicare Provider Summary: **2014 - 2021**"),
                     subtitle = gt::md("Provider: **SARAH K. HUSSAIN, MD**"),
                     divider = c("year", "tot_srvcs"),
                     dollars = c("tot_charges", "tot_allowed", "tot_payment"),
                     pctchg = c("tot_benes_pct", "tot_srvcs_pct")) |>
  gt::cols_label(tot_benes = "Beneficiaries", 
                 tot_srvcs = "Services",
                 tot_charges = "Charges",
                 tot_allowed = "Allowed",
                 tot_payment = "Payment") |> 
  gt::cols_merge_n_pct(tot_benes, tot_benes_pct) |> 
  gt::cols_merge_n_pct(tot_srvcs, tot_srvcs_pct) |> 
  gtExtras::gt_color_rows(columns = c("tot_charges", "tot_allowed", "tot_payment"))

provider_2 <- provider |> 
  dplyr::select(year, bene_age_avg)

pr_age <- provider |> 
  dplyr::select(year,
                bene_age_lt65,
                bene_age_65_74,
                bene_age_75_84,
                bene_age_gt84) |> 
  dplyr::mutate(bene_age_65_84 = bene_age_65_74 + bene_age_75_84, 
                .keep = "unused", 
                .after = bene_age_lt65) |> 
  tidyr::pivot_longer(cols = c(bene_age_lt65, bene_age_65_84, bene_age_gt84), 
                      names_to = "measure", 
                      values_to = "demo_age") |> 
  dplyr::group_by(year) |> 
  dplyr::summarise(demo_age = list(demo_age), .groups = "drop")

pr_sex <- provider |> 
  dplyr::select(year,
                bene_female,
                bene_male) |> 
  tidyr::pivot_longer(cols = c(bene_female, bene_male), 
                      names_to = "measure", 
                      values_to = "demo_sex") |> 
  dplyr::group_by(year) |> 
  dplyr::summarise(demo_sex = list(demo_sex), .groups = "drop")


pr_stat <- provider |> 
  dplyr::select(year,
                bene_dual,
                bene_ndual) |> 
  tidyr::pivot_longer(cols = c(bene_dual, bene_ndual), 
                      names_to = "measure", 
                      values_to = "demo_stat") |> 
  dplyr::group_by(year) |> 
  dplyr::summarise(demo_stat = list(demo_stat), .groups = "drop")

provider_2 <- provider_2 |> 
  dplyr::left_join(pr_age, by = c("year")) |> 
  dplyr::left_join(pr_sex, by = c("year")) |> 
  dplyr::left_join(pr_stat, by = c("year")) |> 
  provider:::gt_prov(source = gt::md("Source: [Medicare Physician & Other Practitioners: by Provider
                                     API](https://data.cms.gov/provider-summary-by-type-of-service/medicare-physician-other-practitioners/medicare-physician-other-practitioners-by-provider)"),
                     title = gt::md("Medicare Provider Summary: **2014 - 2021**"),
                     subtitle = gt::md("Provider: **SARAH K. HUSSAIN, MD**"),
                     divider = c("year", "bene_age_avg")) |> 
  gt::cols_label(bene_age_avg = "Avg. Age") |> 
  gtExtras::gt_plt_bar_stack(column = demo_age, 
                             width = 60,
                             labels = c("[< 65]  ", " [65-84] ", " [> 84]"),
                             palette = c("#ff4343", "black", "#ff4343")) |> 
  gtExtras::gt_plt_bar_stack(column = demo_sex, 
                             width = 40,
                             labels = c("Female ", " Male"),
                             palette = c("black", "#ff4343")) |> 
  gtExtras::gt_plt_bar_stack(column = demo_stat, 
                             width = 45,
                             labels = c("Dual ", " Non-Dual"),
                             palette = c("black", "#ff4343")) |> 
  gtExtras::gt_color_rows(columns = c("bene_age_avg"))

provider_3 <- provider |> 
  dplyr::select(year,
                "HCC Average Risk Score" = bene_risk_avg,
                "Atrial Fibrillation" = bene_cc_af,
                "Alzheimer’s Disease/Dementia" = bene_cc_alz,
                "Asthma" = bene_cc_asth,
                "Cancer" = bene_cc_canc,
                "Heart Failure" = bene_cc_chf,
                "Chronic Kidney Disease" = bene_cc_ckd,
                "COPD" = bene_cc_copd,
                "Depression" = bene_cc_dep,
                "Diabetes" = bene_cc_diab,
                "Hyperlipidemia" = bene_cc_hplip,
                "Hypertension" = bene_cc_hpten,
                "Ischemic Heart Disease" = bene_cc_ihd,
                "Osteoporosis" = bene_cc_opo,
                "Rheumatoid / Osteoarthritis" = bene_cc_raoa,
                "Schizophrenia / Other Psych" = bene_cc_sz,
                "Stroke" = bene_cc_strk) |> 
  tidyr::pivot_longer(cols = !year, 
                      names_to = "condition", 
                      values_to = "value") |> 
  tidyr::pivot_wider(names_from = year, 
                     values_from = value) |> 
  dplyr::arrange(condition) |> 
  provider:::gt_prov(source = gt::md("Source: [Medicare Physician & Other Practitioners: by Provider
                                     API](https://data.cms.gov/provider-summary-by-type-of-service/medicare-physician-other-practitioners/medicare-physician-other-practitioners-by-provider)"),
                     title = gt::md("Medicare Provider Summary: **2014 - 2021**"),
                     subtitle = gt::md("Provider: **SARAH K. HUSSAIN, MD**"),
                     divider = c("condition"), 
                     pct = c("2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021"),
                     clean = FALSE) |> 
  gt::data_color(columns = !condition, direction = "row", palette = "ggsci::red_material", na_color = "black")
```

</details>

```{r, echo=FALSE, eval=TRUE}
provider_1
```

<br>

```{r, echo=FALSE, eval=TRUE}
provider_2
```

<br>

```{r, echo=FALSE, eval=TRUE}
provider_3
```

<br>

<details><summary>Code</summary>

```{r}
cc_prov <- provider |> 
  dplyr::select(year,
                "Atrial Fibrillation" = bene_cc_af,
                "Alzheimer's Disease/Dementia" = bene_cc_alz,
                "Asthma" = bene_cc_asth,
                "Cancer" = bene_cc_canc,
                "Heart Failure" = bene_cc_chf,
                "Chronic Kidney Disease" = bene_cc_ckd,
                "COPD" = bene_cc_copd,
                "Depression" = bene_cc_dep,
                "Diabetes" = bene_cc_diab,
                "Hyperlipidemia" = bene_cc_hplip,
                "Hypertension" = bene_cc_hpten,
                "Ischemic Heart Disease" = bene_cc_ihd,
                "Osteoporosis" = bene_cc_opo,
                "Rheumatoid / Osteoarthritis" = bene_cc_raoa,
                "Schizophrenia and Other Psychotic Disorders" = bene_cc_sz,
                "Stroke" = bene_cc_strk) |> 
  tidyr::pivot_longer(cols = !year, 
                      names_to = "stat", 
                      values_to = "value") |> 
  tidyr::pivot_wider(names_from = year, 
                     values_from = value) |> 
  dplyr::pull(stat)

cc_nat <- 2014:2018 |> 
  furrr::future_map(\(x) cc_specific(year = x, level = "National", demographic = "All", age_group = "All")) |> 
  purrr::list_rbind() |> 
  dplyr::select(year, level, condition, prevalence) |> 
  dplyr::filter(condition %in% cc_prov)

cc_state <- 2014:2018 |> 
  furrr::future_map(\(x) cc_specific(year = x, level = "State", sublevel = "Pennsylvania", demographic = "All", age_group = "All")) |> 
  purrr::list_rbind() |> 
  dplyr::select(year, level, condition, prevalence) |> 
  dplyr::filter(condition %in% cc_prov)

cc_nat <- cc_nat |> 
  tidyr::pivot_wider(names_from = year, 
                     values_from = prevalence)

cc_state <- cc_state |> 
  tidyr::pivot_wider(names_from = year, 
                     values_from = prevalence)

cc_all <- dplyr::bind_rows(cc_nat, cc_state) |> 
  provider:::gt_prov(source = gt::md("Source: [Medicare Specific Chronic Conditions](https://data.cms.gov/medicare-chronic-conditions/specific-chronic-conditions)"),
                     title = gt::md("Medicare Chronic Conditions: **2014 - 2018**"),
                     subtitle = gt::md("National and State Level"),
                     divider = c("condition"), 
                     pct = c("2014", "2015", "2016", "2017", "2018"),
                     clean = FALSE) |> 
  gt::tab_row_group(label = gt::md("**NATIONAL**"), rows = level == "National") |> 
  gt::tab_row_group(label = gt::md("**STATE**"), rows = level == "State") |> 
  gt::cols_hide(columns = c(level))
```

</details>

```{r, echo=FALSE, eval=TRUE}
cc_all
```


```r
2014:2021 |> 
  furrr::future_map(\(x) physician_by_service(year = x, npi = 1043477615)) |> 
  purrr::list_rbind()
```

<details><summary>Code</summary>


```{r}
service <- 2014:2021 |> 
  furrr::future_map(\(x) physician_by_service(year = x, npi = 1043477615)) |> 
  purrr::list_rbind()

srvc_ind <- service |> 
  dplyr::select(year, 
                hcpcs_code,
                hcpcs_desc,
                place_of_srvc,
                tot_benes,
                tot_srvcs,
                avg_charges,
                avg_allowed,
                avg_payment) |> 
  dplyr::mutate(sublevel = "Individual", .after = year)

srvc <- service |> 
  dplyr::select(year, 
                hcpcs_code,
                place_of_srvc)

srvc_nat <- furrr::future_pmap(srvc, 
                               physician_by_geography, 
                               level = "National") |>
  purrr::list_rbind() |> 
  dplyr::select(year, 
                sublevel,
                hcpcs_code,
                hcpcs_desc,
                place_of_srvc,
                tot_benes,
                tot_srvcs,
                avg_charges,
                avg_allowed,
                avg_payment)

srvc_state <- furrr::future_pmap(srvc, 
                                 physician_by_geography, 
                                 level = "State", 
                                 sublevel = "Pennsylvania") |>
  purrr::list_rbind() |> 
  dplyr::select(year, 
                sublevel,
                hcpcs_code,
                hcpcs_desc,
                place_of_srvc,
                tot_benes,
                tot_srvcs,
                avg_charges,
                avg_allowed,
                avg_payment)

gt_sum <- dplyr::bind_rows(srvc_ind, 
                           srvc_state, 
                           srvc_nat) |> 
  tidyr::unite("hcpcs", 
               c(hcpcs_code, place_of_srvc), 
               remove = TRUE, 
               sep = " : ") |> 
  dplyr::group_by(sublevel, hcpcs) |> 
  dplyr::summarize(avg_charges = mean(avg_charges),
                   avg_allowed = mean(avg_allowed),
                   avg_payment = mean(avg_payment),
                   .groups = "drop") |> 
  tidyr::pivot_longer(cols = dplyr::contains("avg_"), 
                      names_to = "type", 
                      values_to = "amount") |> 
  tidyr::pivot_wider(names_from = sublevel, 
                     values_from = amount) |> 
  dplyr::mutate(type = stringr::str_remove(type, "avg_")) |> 
  dplyr::arrange(hcpcs) |> 
  provider:::gt_prov(source = gt::md("Source: [Medicare Physician & Other Practitioners: by Provider and Service API](https://data.cms.gov/provider-summary-by-type-of-service/medicare-physician-other-practitioners/medicare-physician-other-practitioners-by-provider-and-service)"),
                     title = gt::md("Medicare Provider Summary: **2014 - 2018**"),
                     subtitle = gt::md("Comparing HCPCS Reimbursement Data at the **National**, **State**, and **Individual** Level"),
                     divider = c("hcpcs"),
                     dollars = c("Individual", "National", "Pennsylvania"))
```

</details>


```{r, echo=FALSE, eval=TRUE}
gt_sum
```


```{r echo=FALSE, eval=FALSE, include=FALSE}
gt_table <- mpop_13_20 |>
  dplyr::select(year,
                hcpcs     = hcpcs_cd,
                benefits  = tot_benes,
                services  = tot_srvcs,
                avg_bill  = avg_sbmtd_chrg,
                avg_allow = avg_mdcr_alowd_amt,
                avg_pay   = avg_mdcr_pymt_amt) |> 
  dplyr::group_by(hcpcs) |> 
  dplyr::summarize(
    ben_sum    = sum(benefits),
    ben_mean   = mean(benefits),
    ben_spark  = list(benefits),
    serv_sum   = sum(services),
    serv_mean  = mean(services),
    serv_spark = list(services),
    char_sum   = sum(avg_bill),
    char_mean  = mean(avg_bill),
    char_spark = list(avg_bill),
    all_sum    = sum(avg_allow),
    all_mean   = mean(avg_allow),
    all_spark  = list(avg_allow),
    pay_sum    = sum(avg_pay),
    pay_mean   = mean(avg_pay),
    pay_spark  = list(avg_pay),
    .groups = "drop") |> 
  dplyr::filter(ben_sum > 22) |> 
  dplyr::arrange(desc(ben_sum))


gt_output <- gt_table |> 
  gt::gt() |> 
  gt::tab_header(
  title = gt::md(paste0(mpop_ex_name_cred, "**Medicare Data Report**: 2013 - 2020.")), 
  subtitle = gt::md(
  "NPI: 1760485387. HCPCS Codes with a beneficiary count *less than 30* have been excluded.")) |> 
  gtExtras::gt_theme_538() |> 
  gt::tab_options(footnotes.multiline = TRUE, 
                  table.font.size = "16px",
                  heading.title.font.size = "22px") |> 
  gtExtras::gt_plt_sparkline(ben_spark, 
                             type = "ref_iqr", 
                             fig_dim = c(5, 30), 
                             same_limit = FALSE, 
                             label = FALSE,
                             palette = c("black", 
                                         "black", 
                                         "blue", 
                                         "green", 
                                         "blue")) |> 
  gtExtras::gt_plt_sparkline(serv_spark, 
                             type = "ref_iqr", 
                             fig_dim = c(5, 30), 
                             same_limit = FALSE, 
                             label = FALSE,
                             palette = c("black", 
                                         "black", 
                                         "blue", 
                                         "green", 
                                         "blue")) |> 
  gtExtras::gt_plt_sparkline(char_spark, 
                             type = "ref_iqr", 
                             fig_dim = c(5, 30), 
                             same_limit = FALSE, 
                             label = FALSE,
                             palette = c("black", 
                                         "black", 
                                         "blue", 
                                         "green", 
                                         "orange")) |> 
  gtExtras::gt_plt_sparkline(all_spark, 
                             type = "ref_iqr", 
                             fig_dim = c(5, 30), 
                             same_limit = FALSE, 
                             label = FALSE,
                             palette = c("black", 
                                         "black", 
                                         "blue", 
                                         "green", 
                                         "orange")) |> 
  gtExtras::gt_plt_sparkline(pay_spark, 
                             type = "ref_iqr", 
                             fig_dim = c(5, 30), 
                             same_limit = FALSE, 
                             label = FALSE,
                             palette = c("black", 
                                         "black", 
                                         "blue", 
                                         "green", 
                                         "orange")) |> 
  gtExtras::gt_add_divider(columns = "hcpcs", 
                           style = "solid", 
                           include_labels = FALSE,
                           weight = gt::px(3),
                           color = "gray") |>
  gt::fmt_number(columns = c(ben_sum:ben_mean, 
                             serv_sum:serv_mean), 
                             decimals = 0) |> 
  gt::fmt_currency(columns = c(char_sum:char_mean, 
                               all_sum:all_mean, 
                               pay_sum:pay_mean), 
                               currency = "USD") |> 
  gt::tab_spanner(label = "Beneficiaries", 
                  id = "ben", 
                  columns = c(ben_sum, 
                              ben_mean, 
                              ben_spark)) |> 
  gt::tab_spanner(label = "Services", 
                  id = "serv", 
                  columns = c(serv_sum, 
                              serv_mean, 
                              serv_spark)) |> 
  gt::tab_spanner(label = "Submitted Charge", 
                  columns = c(char_sum,
                              char_mean, 
                              char_spark)) |> 
  gt::tab_spanner(label = "Allowed Amount", 
                  columns = c(all_sum,
                              all_mean, 
                              all_spark)) |> 
  gt::tab_spanner(label = "Payment", 
                  columns = c(pay_sum,
                              pay_mean, 
                              pay_spark)) |> 
  gt::cols_label(ben_sum = "Count", 
                 ben_mean = "Average", 
                 ben_spark = "Trend") |> 
  gt::cols_label(serv_sum = "Count", 
                 serv_mean = "Average", 
                 serv_spark = "Trend") |> 
  gt::cols_label(char_sum = "Sum",
                 char_mean = "Average", 
                 char_spark = "Trend") |> 
  gt::cols_label(all_sum = "Sum",
                 all_mean = "Average", 
                 all_spark = "Trend") |> 
  gt::cols_label(pay_sum = "Sum", 
                 pay_mean = "Average", 
                 pay_spark = "Trend") |> 
  gt::tab_source_note(
    source_note = gt::md("Data Source: **Medicare** Physician & Other Practitioners by Provider and Service, 2013 - 2020.")) |> 
  gt::tab_footnote(
    footnote = gt::md("Number of *distinct* Medicare beneficiaries receiving the service for each HCPCS code."), 
    locations = gt::cells_column_spanners(spanners = "ben")) |> 
  gt::tab_footnote(
    footnote = gt::md("Number of services provided. *Note: The metrics used to count the number provided can vary from service to service.*"),
    locations = gt::cells_column_spanners(spanners = "serv")) |> 
  gtExtras::gt_color_rows(columns = ben_sum, 
                          palette = "RColorBrewer::Blues", pal_type = "continuous", domain = range(gt_table$ben_sum)) |> 
  gtExtras::gt_color_rows(columns = ben_mean, 
                          palette = "RColorBrewer::Blues", pal_type = "continuous", domain = range(gt_table$ben_mean)) |> 
  gtExtras::gt_color_rows(columns = serv_sum, 
                          palette = "RColorBrewer::Blues", pal_type = "continuous", domain = range(gt_table$serv_sum)) |> 
  gtExtras::gt_color_rows(columns = serv_mean, 
                          palette = "RColorBrewer::Blues", pal_type = "continuous", domain = range(gt_table$serv_mean)) |> 
  gtExtras::gt_color_rows(columns = char_sum, 
                          palette = "RColorBrewer::Oranges", pal_type = "continuous", domain = range(gt_table$char_sum)) |> 
  gtExtras::gt_color_rows(columns = char_mean, 
                          palette = "RColorBrewer::Oranges", pal_type = "continuous", domain = range(gt_table$char_mean)) |> 
  gtExtras::gt_color_rows(columns = all_sum, 
                          palette = "RColorBrewer::Oranges", pal_type = "continuous", domain = range(gt_table$all_sum)) |> 
  gtExtras::gt_color_rows(columns = all_mean, 
                          palette = "RColorBrewer::Oranges", pal_type = "continuous", domain = range(gt_table$all_mean)) |> 
  gtExtras::gt_color_rows(columns = pay_sum, 
                          palette = "RColorBrewer::Oranges", pal_type = "continuous", domain = range(gt_table$pay_sum)) |> 
  gtExtras::gt_color_rows(columns = pay_mean, 
                          palette = "RColorBrewer::Oranges", pal_type = "continuous", domain = range(gt_table$pay_mean)) |> 
  gt::opt_vertical_padding(scale = 1.5)
```

