test_that("cols_bene() works", {
  x <- dplyr::tibble(
    year                                         = 1,
    month                                        = 1,
    bene_geo_lvl                                 = 1,
    bene_state_abrvtn                            = 1,
    bene_state_desc                              = 1,
    bene_county_desc                             = 1,
    bene_fips_cd                                 = 1,
    tot_benes                                    = 1,
    orgnl_mdcr_benes                             = 1,
    ma_and_oth_benes                             = 1,
    aged_tot_benes                               = 1,
    aged_esrd_benes                              = 1,
    aged_no_esrd_benes                           = 1,
    dsbld_tot_benes                              = 1,
    dsbld_esrd_and_esrd_only_benes               = 1,
    dsbld_no_esrd_benes                          = 1,
    a_b_tot_benes                                = 1,
    a_b_orgnl_mdcr_benes                         = 1,
    a_b_ma_and_oth_benes                         = 1,
    prscrptn_drug_tot_benes                      = 1,
    prscrptn_drug_pdp_benes                      = 1,
    prscrptn_drug_mapd_benes                     = 1,
    prscrptn_drug_deemed_eligible_full_lis_benes = 1,
    prscrptn_drug_full_lis_benes                 = 1,
    prscrptn_drug_partial_lis_benes              = 1,
    prscrptn_drug_no_lis_benes                   = 1)

  y <- dplyr::tibble(year              = 1,
                     period            = 1,
                     level             = 1,
                     state             = 1,
                     state_name        = 1,
                     county            = 1,
                     fips              = 1,
                     bene_total        = 1,
                     bene_orig         = 1,
                     bene_ma_oth       = 1,
                     bene_total_aged   = 1,
                     bene_aged_esrd    = 1,
                     bene_aged_no_esrd = 1,
                     bene_total_dsb    = 1,
                     bene_dsb_esrd     = 1,
                     bene_dsb_no_esrd  = 1,
                     bene_total_ab     = 1,
                     bene_ab_orig      = 1,
                     bene_ab_ma_oth    = 1,
                     bene_total_rx     = 1,
                     bene_rx_pdp       = 1,
                     bene_rx_mapd      = 1,
                     bene_rx_lis_elig  = 1,
                     bene_rx_lis_full  = 1,
                     bene_rx_lis_part  = 1,
                     bene_rx_lis_no    = 1)
  expect_equal(cols_bene(x), y)
})

test_that("cols_betos() works", {
x <- dplyr::tibble(
    hcpcs_cd               = 1,
    rbcs_id                = 1,
    'rbcs_cat'             = 1,
    rbcs_cat_desc          = 1,
    'rbcs_cat_subcat'      = 1,
    rbcs_subcat_desc       = 1,
    'rbcs_fam_numb'        = 1,
    rbcs_family_desc       = 1,
    rbcs_major_ind         = 1,
    hcpcs_cd_add_dt        = 1,
    hcpcs_cd_end_dt        = 1,
    rbcs_assignment_eff_dt = 1,
    rbcs_assignment_end_dt = 1)

  y <- dplyr::tibble(hcpcs            = 1,
                     rbcs_id          = 1,
                     category         = 1,
                     subcategory      = 1,
                     family           = 1,
                     procedure        = 1,
                     hcpcs_start_date = 1,
                     hcpcs_end_date   = 1,
                     rbcs_start_date  = 1,
                     rbcs_end_date    = 1)
  expect_equal(cols_betos(x), y)
})

test_that("cols_hosp() works", {
  x <- dplyr::tibble(
    npi                          = 1,
    associate_id                 = 1,
    enrollment_id                = 1,
    enrollment_state             = 1,
    ccn                          = 1,
    organization_name            = 1,
    doing_business_as_name       = 1,
    provider_type_code           = 1,
    provider_type_text           = 1,
    incorporation_date           = 1,
    incorporation_state          = 1,
    structure                    = 1,
    address                      = 1,
    city                         = 1,
    state                        = 1,
    zip_code                     = 1,
    location_type                = 1,
    proprietary_nonprofit        = 1,
    multiple_npi_flag            = 1,
    reh_conversion_flag          = 1,
    reh_conversion_date          = 1,
    cah_or_hospital_ccn          = 1,
    subgroup_general             = 1,
    subgroup_acute_care          = 1,
    subgroup_alcohol_drug        = 1,
    subgroup_childrens           = 1,
    subgroup_long_term           = 1,
    subgroup_psychiatric         = 1,
    subgroup_rehabilitation      = 1,
    subgroup_short_term          = 1,
    subgroup_swing_bed_approved  = 1,
    subgroup_psychiatric_unit    = 1,
    subgroup_rehabilitation_unit = 1,
    subgroup_specialty_hospital  = 1,
    subgroup_other               = 1,
    subgroup_other_text          = 1)

  y <- dplyr::tibble(
    npi                          = 1,
    pac_org                      = 1,
    enid_org                     = 1,
    enid_state                   = 1,
    facility_ccn                 = 1,
    organization                 = 1,
    doing_business_as            = 1,
    specialty_code               = 1,
    specialty                    = 1,
    incorp_date                  = 1,
    incorp_state                 = 1,
    structure                    = 1,
    address                      = 1,
    city                         = 1,
    state                        = 1,
    zip                          = 1,
    location_type                = 1,
    registration                 = 1,
    multi_npi                    = 1,
    reh_conversion               = 1,
    reh_date                     = 1,
    reh_ccns                     = 1,
    subgroup_general             = 1,
    subgroup_acute_care          = 1,
    subgroup_alcohol_drug        = 1,
    subgroup_childrens           = 1,
    subgroup_long_term           = 1,
    subgroup_psychiatric         = 1,
    subgroup_rehabilitation      = 1,
    subgroup_short_term          = 1,
    subgroup_swing_bed_approved  = 1,
    subgroup_psychiatric_unit    = 1,
    subgroup_rehabilitation_unit = 1,
    subgroup_specialty_hospital  = 1,
    subgroup_other               = 1,
    other                        = 1)

  yy <- dplyr::tibble(
    npi_org                        = 1,
    pac_org                        = 1,
    enid_org                       = 1,
    enid_state                     = 1,
    facility_ccn                   = 1,
    organization                   = 1,
    doing_business_as              = 1,
    specialty_code                 = 1,
    specialty                      = 1,
    incorp_date                    = 1,
    incorp_state                   = 1,
    structure                      = 1,
    address                        = 1,
    city                           = 1,
    state                          = 1,
    zip                            = 1,
    location_type                  = 1,
    registration                   = 1,
    multi_npi                      = 1,
    reh_date                       = 1,
    reh_ccns                       = 1,
    reh_conversion                 = 1,
    `Subgroup General`             = 1,
    `Subgroup Acute Care`          = 1,
    `Subgroup Alcohol Drug`        = 1,
    `Subgroup Childrens' Hospital` = 1,
    `Subgroup Long-term`           = 1,
    `Subgroup Psychiatric`         = 1,
    `Subgroup Rehabilitation`      = 1,
    `Subgroup Short-Term`          = 1,
    `Subgroup Swing-Bed Approved`  = 1,
    `Subgroup Psychiatric Unit`    = 1,
    `Subgroup Rehabilitation Unit` = 1,
    `Subgroup Specialty Hospital`  = 1,
    `Subgroup Other`               = 1,
    other                          = 1)

  expect_equal(cols_hosp(x, 1), y)
  expect_equal(cols_hosp(y, 2), yy)
})

test_that("cols_opt() works", {
  x <- dplyr::tibble(
    npi                         = 1,
    first_name                  = 1,
    last_name                   = 1,
    specialty                   = 1,
    eligible_to_order_and_refer = 1,
    optout_effective_date       = 1,
    optout_end_date             = 1,
    last_updated                = 1,
    address                     = 1,
    city_name                   = 1,
    state_code                  = 1,
    zip_code                    = 1)

  y <- dplyr::tibble(
    npi               = 1,
    first             = 1,
    last              = 1,
    specialty         = 1,
    order_refer       = 1,
    optout_start_date = 1,
    optout_end_date   = 1,
    last_updated      = 1,
    address           = 1,
    city              = 1,
    state             = 1,
    zip               = 1)

  expect_equal(cols_opt(x), y)
})

test_that("cols_ord() works", {
  x <- dplyr::tibble(
    npi        = 1,
    first_name = 1,
    last_name  = 1,
    partb      = 1,
    hha        = 1,
    dme        = 1,
    pmd        = 1)

  y <- dplyr::tibble(
    npi                         = 1,
    first                       = 1,
    last                        = 1,
    `Medicare Part B`           = 1,
    `Home Health Agency`        = 1,
    `Durable Medical Equipment` = 1,
    `Power Mobility Devices`    = 1)

  expect_equal(cols_ord(x), y)
})

test_that("cols_pros() works", {
  x <- dplyr::tibble(
    npi                = 1,
    pecos_asct_cntl_id = 1,
    enrlmt_id          = 1,
    provider_type_cd   = 1,
    provider_type_desc = 1,
    state_cd           = 1,
    org_name           = 1,
    first_name         = 1,
    mdl_name           = 1,
    last_name          = 1,
    gndr_sw            = 1)

  y <- dplyr::tibble(
    npi                   = 1,
    pac                   = 1,
    enid                  = 1,
    specialty_code        = 1,
    specialty_description = 1,
    state                 = 1,
    organization          = 1,
    first                 = 1,
    middle                = 1,
    last                  = 1,
    gender                = 1)

  expect_equal(cols_pros(x), y)
})

test_that("cols_qpp() works", {

  x <- dplyr::tibble(
    year                                         = 1,
    npi                                          = 1,
    practice_state_or_us_territory               = 1,
    practice_size                                = 1,
    clinician_specialty                          = 1,
    years_in_medicare                            = 1,
    participation_type                           = 1,
    medicare_patients                            = 1,
    services                                     = 1,
    allowed_charges                              = 1,
    final_score                                  = 1,
    payment_adjustment_percentage                = 1,
    quality_category_score                       = 1,
    promoting_interoperability_pi_category_score = 1,
    ia_score                                     = 1,
    cost_score                                   = 1,
    complex_patient_bonus                        = 1,
    quality_improvement_bonus                    = 1,
    quality_bonus                                = 1,
    engaged                                      = 1,
    opted_into_mips                              = 1,
    small_practitioner                           = 1,
    rural_clinician                              = 1,
    hpsa_clinician                               = 1,
    ambulatory_surgical_center                   = 1,
    hospital_based_clinician                     = 1,
    non_patient_facing                           = 1,
    facility_based                               = 1,
    extreme_hardship                             = 1,
    extreme_hardship_quality                     = 1,
    extreme_hardship_pi                          = 1,
    pi_hardship                                  = 1,
    pi_reweighting                               = 1,
    pi_bonus                                     = 1,
    pi_cehrt_id                                  = 1,
    extreme_hardship_ia                          = 1,
    ia_study                                     = 1,
    extreme_hardship_cost                        = 1,
    quality_measure_id_1                         = 1,
    quality_measure_id_2                         = 1,
    quality_measure_id_3                         = 1,
    quality_measure_id_4                         = 1,
    quality_measure_id_5                         = 1,
    quality_measure_id_6                         = 1,
    quality_measure_id_7                         = 1,
    quality_measure_id_8                         = 1,
    quality_measure_id_9                         = 1,
    quality_measure_id_10                        = 1,
    quality_measure_score_1                      = 1,
    quality_measure_score_2                      = 1,
    quality_measure_score_3                      = 1,
    quality_measure_score_4                      = 1,
    quality_measure_score_5                      = 1,
    quality_measure_score_6                      = 1,
    quality_measure_score_7                      = 1,
    quality_measure_score_8                      = 1,
    quality_measure_score_9                      = 1,
    quality_measure_score_10                     = 1,
    pi_measure_id_1                              = 1,
    pi_measure_id_2                              = 1,
    pi_measure_id_3                              = 1,
    pi_measure_id_4                              = 1,
    pi_measure_id_5                              = 1,
    pi_measure_id_6                              = 1,
    pi_measure_id_7                              = 1,
    pi_measure_id_8                              = 1,
    pi_measure_id_9                              = 1,
    pi_measure_id_10                             = 1,
    pi_measure_id_11                             = 1,
    pi_measure_score_1                           = 1,
    pi_measure_score_2                           = 1,
    pi_measure_score_3                           = 1,
    pi_measure_score_4                           = 1,
    pi_measure_score_5                           = 1,
    pi_measure_score_6                           = 1,
    pi_measure_score_7                           = 1,
    pi_measure_score_8                           = 1,
    pi_measure_score_9                           = 1,
    pi_measure_score_10                          = 1,
    pi_measure_score_11                          = 1,
    ia_measure_id_1                              = 1,
    ia_measure_id_2                              = 1,
    ia_measure_id_3                              = 1,
    ia_measure_id_4                              = 1,
    ia_measure_score_1                           = 1,
    ia_measure_score_2                           = 1,
    ia_measure_score_3                           = 1,
    ia_measure_score_4                           = 1,
    cost_measure_id_1                            = 1,
    cost_measure_id_2                            = 1,
    cost_measure_score_1                         = 1,
    cost_measure_score_2                         = 1)

  y <- dplyr::tibble(
    year                         = 1,
    npi                          = 1,
    state                        = 1,
    org_size                     = 1,
    specialty                    = 1,
    # med_years                    = 1,
    participation_type           = 1,
    beneficiaries                = 1,
    services                     = 1,
    allowed_charges              = 1,
    final_score                  = 1,
    pay_adjust                   = 1,
    quality_score                = 1,
    pi_score                     = 1,
    ia_score                     = 1,
    cost_score                   = 1,
    complex_bonus                = 1,
    qi_bonus                     = 1,
    ind_quality_bonus            = 1,
    ind_engaged                  = 1,
    ind_opted_into_mips          = 1,
    ind_small_practitioner       = 1,
    ind_rural                    = 1,
    ind_hpsa                     = 1,
    ind_asc                      = 1,
    ind_hospital_based           = 1,
    ind_non_patient_facing       = 1,
    ind_facility_based           = 1,
    ind_extreme_hardship         = 1,
    ind_extreme_hardship_quality = 1,
    ind_extreme_hardship_pi      = 1,
    ind_pi_hardship              = 1,
    ind_pi_reweighting           = 1,
    ind_pi_bonus                 = 1,
    # pi_cehrt_id                  = 1,
    ind_extreme_hardship_ia      = 1,
    ind_ia_study                 = 1,
    ind_extreme_hardship_cost    = 1,
    quality_measure_id_1         = 1,
    quality_measure_id_2         = 1,
    quality_measure_id_3         = 1,
    quality_measure_id_4         = 1,
    quality_measure_id_5         = 1,
    quality_measure_id_6         = 1,
    quality_measure_id_7         = 1,
    quality_measure_id_8         = 1,
    quality_measure_id_9         = 1,
    quality_measure_id_10        = 1,
    quality_measure_score_1      = 1,
    quality_measure_score_2      = 1,
    quality_measure_score_3      = 1,
    quality_measure_score_4      = 1,
    quality_measure_score_5      = 1,
    quality_measure_score_6      = 1,
    quality_measure_score_7      = 1,
    quality_measure_score_8      = 1,
    quality_measure_score_9      = 1,
    quality_measure_score_10     = 1,
    pi_measure_id_1              = 1,
    pi_measure_id_2              = 1,
    pi_measure_id_3              = 1,
    pi_measure_id_4              = 1,
    pi_measure_id_5              = 1,
    pi_measure_id_6              = 1,
    pi_measure_id_7              = 1,
    pi_measure_id_8              = 1,
    pi_measure_id_9              = 1,
    pi_measure_id_10             = 1,
    pi_measure_id_11             = 1,
    pi_measure_score_1           = 1,
    pi_measure_score_2           = 1,
    pi_measure_score_3           = 1,
    pi_measure_score_4           = 1,
    pi_measure_score_5           = 1,
    pi_measure_score_6           = 1,
    pi_measure_score_7           = 1,
    pi_measure_score_8           = 1,
    pi_measure_score_9           = 1,
    pi_measure_score_10          = 1,
    pi_measure_score_11          = 1,
    ia_measure_id_1              = 1,
    ia_measure_id_2              = 1,
    ia_measure_id_3              = 1,
    ia_measure_id_4              = 1,
    ia_measure_score_1           = 1,
    ia_measure_score_2           = 1,
    ia_measure_score_3           = 1,
    ia_measure_score_4           = 1,
    cost_measure_id_1            = 1,
    cost_measure_id_2            = 1,
    cost_measure_score_1         = 1,
    cost_measure_score_2         = 1)

  z <- dplyr::tibble(
    year = 1,
    npi = 1,
    state = 1,
    org_size = 1,
    specialty = 1,
    # med_years = 1,
    participation_type = 1,
    beneficiaries = 1,
    services = 1,
    allowed_charges = 1,
    final_score     = 1,
    pay_adjust      = 1,
    quality_score   = 1,
    pi_score        = 1,
    ia_score        = 1,
    cost_score      = 1,
    complex_bonus   = 1,
    qi_bonus        = 1,
    # pi_cehrt_id     = 1,
    qpp_status        = 1,
    qpp_measures        = 1)

  zz <- dplyr::tibble(
    year = 1,
    npi = 1,
    state = 1,
    org_size = 1,
    specialty = 1,
    # med_years = 1,
    participation_type = 1,
    beneficiaries = 1,
    services = 1,
    allowed_charges = 1,
    final_score     = 1,
    pay_adjust      = 1,
    quality_score   = 1,
    pi_score        = 1,
    ia_score        = 1,
    cost_score      = 1,
    complex_bonus   = 1,
    qi_bonus        = 1,
    # pi_cehrt_id     = 1,
    qpp_status = 1,
    qpp_measures = 1)

  expect_equal(cols_qpp(x, step = "tidy"), y)
  expect_equal(cols_qpp(z, step = "nest"), zz)
})

test_that("cols_reas() works", {

  x <- dplyr::tibble(
    individual_npi                               = 1,
    individual_pac_id                            = 1,
    individual_enrollment_id                     = 1,
    individual_first_name                        = 1,
    individual_last_name                         = 1,
    individual_total_employer_associations       = 1,
    group_legal_business_name                    = 1,
    group_pac_id                                 = 1,
    group_enrollment_id                          = 1,
    group_state_code                             = 1,
    group_reassignments_and_physician_assistants = 1,
    individual_state_code                        = 1,
    individual_specialty_description             = 1,
    individual_due_date                          = 1,
    group_due_date                               = 1,
    record_type                                  = 1)

  y <- dplyr::tibble(
    npi           = 1,
    pac           = 1,
    enid          = 1,
    first         = 1,
    last          = 1,
    associations  = 1,
    organization  = 1,
    pac_org       = 1,
    enid_org      = 1,
    state_org     = 1,
    reassignments = 1,
    entry         = 1)

  expect_equal(cols_reas(x), y)
})

# c('npi' = 'individual_npi') |>
#   tibble::enframe() |>
#   tibble::add_column(z = 1) |>
#   dplyr::select(name, z) |>
#   datawizard::data_rotate(colnames = "name") |>
#   dplyr::tibble() |>
#   constructive::construct()
