---
title: "API Overviews"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse  = TRUE,
  echo      = TRUE, 
  message   = FALSE, 
  warning   = FALSE,
  error     = TRUE,
  comment   = "#>",
  dpi       = 300, 
  out.width = "100%",
  fig.path  = "man/figures/README-"
)
```

## API Articles

```{r echo=FALSE, eval=TRUE}
ben_art <- gluedown::md_link("Beneficiary Enrollment" = "https://andrewallenbruce.github.io/provider/articles/beneficiary-enrollment.html")
ccm_art <- gluedown::md_link("Chronic Conditions (Multiple)" = "https://andrewallenbruce.github.io/provider/articles/mcr-chron-cond.html")
ccs_art <- gluedown::md_link("Chronic Conditions (Specific)" = "https://andrewallenbruce.github.io/provider/articles/mcr-chron-cond.html")
drs_art <- gluedown::md_link("Doctors and Clinicians" = "https://andrewallenbruce.github.io/provider/articles/dcotors-and-clinicians.html")
fac_art <- gluedown::md_link("Facility Affiliations" = "https://andrewallenbruce.github.io/provider/articles/facility-affiliations.html")
hos_art <- gluedown::md_link("Hospital Enrollment" = "https://andrewallenbruce.github.io/provider/articles/hospital-enrollment.html")
mis_art <- gluedown::md_link("Missing Information" = "https://andrewallenbruce.github.io/provider/articles/missing-info.html")
npi_art <- gluedown::md_link("NPPES NPI Registry" = "https://andrewallenbruce.github.io/provider/articles/nppes-npi-registry.html")
opp_art <- gluedown::md_link("Open Payments Program" = "https://andrewallenbruce.github.io/provider/articles/cms-open-payments.html")
opt_art <- gluedown::md_link("Opt Out Affidavits" = "https://andrewallenbruce.github.io/provider/articles/opt-out.html")
ord_art <- gluedown::md_link("Order and Referring Eligibility" = "https://andrewallenbruce.github.io/provider/articles/order-refer.html")
pap_art <- gluedown::md_link("Pending Medicare Applications" = "https://andrewallenbruce.github.io/provider/articles/pending-applications.html")
pbg_art <- gluedown::md_link("Physician by Geography" = "https://andrewallenbruce.github.io/provider/articles/physician-by-geography.html")
pbp_art <- gluedown::md_link("Physician by Provider" = "https://andrewallenbruce.github.io/provider/articles/physician-by-provider.html")
pbs_art <- gluedown::md_link("Physician by Service" = "https://andrewallenbruce.github.io/provider/articles/physician-by-service.html")
pre_art <- gluedown::md_link("Provider Enrollment" = "https://andrewallenbruce.github.io/provider/articles/provider-enrollment.html")
qpp_art <- gluedown::md_link("Quality Payment Program" = "https://andrewallenbruce.github.io/provider/articles/quality-payment.html")
red_art <- gluedown::md_link("Revalidation Date" = "https://andrewallenbruce.github.io/provider/articles/mcr-revalidation.html")
reg_art <- gluedown::md_link("Revalidation Group" = "https://andrewallenbruce.github.io/provider/articles/mcr-revalidation.html")
rer_art <- gluedown::md_link("Revalidation Reassignment" = "https://andrewallenbruce.github.io/provider/articles/mcr-revalidation.html")
tax_art <- gluedown::md_link("Taxonomy Crosswalk" = "https://andrewallenbruce.github.io/provider/articles/mcr-taxon-crosswalk.html")
```

```{r results='asis', echo=FALSE, eval=TRUE}
gluedown::md_order(c(ben_art, 
                     ccm_art,
                     ccs_art,
                     drs_art,
                     fac_art,
                     hos_art,
                     mis_art,
                     npi_art,
                     opp_art,
                     opt_art,
                     ord_art,
                     pap_art,
                     pbg_art,
                     pbp_art,
                     pbs_art,
                     pre_art,
                     qpp_art,
                     red_art,
                     reg_art,
                     rer_art,
                     tax_art))
```

