---
title: "Doctors and Clinicians"
output: html_document
---

```{r include = FALSE}
knitr::opts_chunk$set(
  collapse  = TRUE,
  echo      = TRUE, 
  message   = FALSE, 
  warning   = FALSE,
  error     = TRUE,
  comment   = "#>",
  dpi       = 300, 
  out.width = "100%",
  fig.path  = "man/figures/README-"
)
```

```{r}
library(provider)
```

<br>

The Doctors and Clinicians national downloadable file is organized such that each line is unique at the clinician/enrollment record/group/address level. Clinicians with multiple Medicare enrollment records and/or single enrollments linking to multiple practice locations are listed on multiple lines.

<br>

## Examples


```{r}
doctors_and_clinicians(npi = 1407263999)
```

<br><br>

```{r}
doctors_and_clinicians(school = "NEW YORK UNIVERSITY SCHOOL OF MEDICINE", 
                       grad_year = 2000, 
                       state = "FL")
```

<br><br>

### Data Dictionary

```{r echo=FALSE}
tibble::tibble(
  Variable = c(
    "`npi`",
    "`pac_id`",
    "`enroll_id`",
    "`first_name`",
    "`middle_name`",
    "`last_name`",
    "`suffix`",
    "`gender`",
    "`credential`",
    "`school`",
    "`grad_year`",
    "`specialty`",
    "`specialty_sec`",
    "`telehealth`",
    "`org_name`",
    "`org_pac_id`",
    "`org_members`",
    "`address`",
    "`city`",
    "`state`",
    "`zipcode`",
    "`phone`",
    "`ind_assn`",
    "`group_assn`"
    ),
  Description = c(
    "National Provider Identifier",
    "PAC ID",
    "Clinician Enrollment ID",
    "First Name",
    "Middle Name",
    "Last Name", 
    "Suffix",
    "Gender",
    "Credential",
    "Medical school name",
    "Graduation year",
    "Primary specialty",
    "Secondary specialties",
    "Telehealth",
    "Organization legal name",
    "Group PAC ID",
    "Number of group members",
    "Address",
    "City",
    "State",
    "Zip Code",
    "Phone Number",
    "Clinician accepts Medicare Assignment",
    "Group accepts Medicare Assignment"
    ),
  Definition = c(
    "Unique clinician ID assigned by NPPES.", 
    "Unique individual clinician ID assigned by PECOS.", 
    "Unique ID for the clinician enrollment that is the source for the data in the observation.",
    "Individual clinician first name.",
    "Individual clinician middle name.",
    "Individual clinician last name.",
    "Individual clinician suffix.",
    "Individual clinician gender.",
    "Medical credential such as MD, DO, DPM, etc.",
    "Individual clinician’s medical school.",
    "Individual clinician’s medical school graduation year.",
    "Primary medical specialty reported by the individual clinician in the selected enrollment.",
    "All secondary medical specialty reported by the individual clinician in the selected enrollment.",
    "Indicator for whether clinician offers telehealth services over video and/or audio.  `Y` = Medicare fee-for-service claims indicate that clinician offers telehealth services.",
    "Legal name of the group that the individual clinician works with – will be blank if the address is not linked to a group.",
    "Unique group ID assigned by PECOS to the group that the individual clinician works with – will be blank if the address is not linked to a group.",
    "Total number of individual clinicians affiliated with the group based on Group Practice PAC ID.",
    "Group or individual's address.",
    "Group or individual's city.",
    "Group or individual's state.",
    "Group or individual's zip code (9 digits when available).",
    "Group or individual's phone number. Phone number is listed only when there is a single phone number available for the address.",
    "Indicator for whether clinician accepts Medicare approved amount as payment in full. `Y` = Clinician accepts Medicare approved amount as payment in full.  `M` = Clinician may accept Medicare Assignment.",
    "Indicator for whether group accepts Medicare approved amount as payment in full. `Y` = Group accepts Medicare approved amount as payment in full.  `M` = Group may accept Medicare Assignment."
    )) |> 
  provider:::gt_datadict()
```
