---
title: "Facility Affiliations"
output: html_document
---

```{r include = FALSE}
knitr::opts_chunk$set(
  collapse  = TRUE,
  echo      = TRUE, 
  message   = FALSE, 
  warning   = FALSE,
  error     = TRUE,
  comment   = "#>",
  dpi       = 300, 
  out.width = "100%",
  fig.path  = "man/figures/README-"
)
```

```{r setup}
library(provider)
```


<br>

Facility affiliations data publicly reported in the Provider Data Catalog.

<br>

## Search Examples

```{r}
facility_affiliations(npi = 1003019563)
```

<br>

```{r}
facility_affiliations(facility_ccn = "060004")
```

<br>

```{r}
facility_affiliations(parent_ccn = 670055)
```

<br>

```{r}
facility_affiliations(first_name = "John", 
                      last_name = "Hill", 
                      facility_type = "Home Health Agency")
```

<br><br>

### Data Dictionary

```{r echo=FALSE}
tibble::tibble(
  Variable = c(
    "`npi`",
    "`pac_id`",
    "`first_name`",
    "`middle_name`",
    "`last_name`",
    "`suffix`",
    "`facility_type`",
    "`facility_ccn`",
    "`parent_ccn`"
    ),
  Description = c(
    "National Provider Identifier", 
    "Provider Associate Level ID (PAC ID)",
    "First Name",
    "Middle Name",
    "Last Name", 
    "Suffix",
    "Facility Type",
    "Facility Affiliations CCN",
    "Facility Affiliations Parent CCN"
    ),
  Definition = c(
    "Unique clinician ID assigned by NPPES.", 
    "Unique individual clinician ID assigned by PECOS.",
    "Individual clinician first name.",
    "Individual clinician middle name.",
    "Individual clinician last name.",
    "Individual clinician suffix.",
    "Facilities can fall into the following type categories: Hospital, Long-term Care Hospital, Nursing Home, Inpatient Rehabilitation Facility, Home Health Agency, Hospice, and Dialysis Facility.",
    "Medicare CCN of facility type or unit within hospital where an individual clinician provides service.",
    "Medicare CCN of the primary hospital where individual clinician provides service, should the clinician provide services in a unit within the hospital."
    )) |> 
  provider:::gt_datadict()
```
