---
title: "Mapping Providers"
description: "Demographics, Patient Mix, and Performance"
author: "Andrew Bruce"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse  = FALSE,
  echo      = TRUE, 
  message   = FALSE, 
  warning   = FALSE,
  error     = TRUE,
  comment   = "#>",
  dpi       = 600, 
  out.width = "100%",
  fig.path  = "man/figures/README-"
)
options(scipen = 999)
```


```{r eval=FALSE}
library(provider)
library(tidygeocoder)
library(purrr)
library(dplyr)
library(stringr)
library(vctrs)
library(campfin)
library(ggplot2)
library(ggsflabel)
library(zipcodeR)
library(fipio)
library(sf)
```


```{r eval=FALSE}
# Retrieve NPIs of all RHCs in Georgia
ga <- providers(state = "GA", specialty_code = "00-17")

# Create character vector of distinct NPIs
npis <- unlist(distinct(ga, npi), use.names = FALSE)

# Retrieve NPPES data for each NPI
nppes <- npis |> map(\(x) nppes(npi = x)) |> list_rbind()

# Create data frames of both practice and location addresses
practice <- nppes |> select(npi, organization, purpose, address, city, state)
location <- nppes |> select(npi, organization, 
         purpose = pr_purpose, 
         address = pr_address, 
         city = pr_city, 
         state = pr_state) |> 
         filter(!is.na(purpose))

# Combine and prepare for geocoding
clean <- vec_rbind(practice, location) |> 
  distinct() |> 
  arrange(npi) |>
  mutate(address = normal_address(address),
         pobox = str_detect(address, "PO BOX")) |>
  filter(pobox == FALSE) |>
  mutate(pobox = NULL) |>
  unite("address", address:state, remove = TRUE, sep = " ")

# Pass to {tidygeocoder}
coords <- geocode(clean, address = address, method = "mapbox", 
               full_results = TRUE, unique_only = FALSE) |> 
       select(npi, organization, purpose, place_name, lat, long)
```


```{r eval=FALSE}
# Retrieve NPIs of all RHCs in Georgia
rhcs <- providers(state = "GA", specialty_code = "00-17") |> 
  distinct(npi) |> 
  pull(npi) |> 
  map(\(x) nppes(npi = x)) |>
  list_rbind()

# Separate & Row-bind LOCATION & PRACTICE Addresses
# Normalize Zip codes
pivoted <- vctrs::vec_rbind(
  dplyr::select(rhcs, npi, organization, on_org_name, org_parent, tx_desc, 
                purpose, address, city, state, zip),
  dplyr::select(rhcs, npi, organization, on_org_name, org_parent, tx_desc, 
                purpose = pr_purpose, 
                address = pr_address, 
                city = pr_city, 
                state = pr_state, 
                zip = pr_zip)) |> 
  dplyr::mutate(zipnorm = zipcodeR::normalize_zip(zip)) |> 
  dplyr::filter(!is.na(purpose))

# ----------------------------------------------
# Prepare for geocoding
clean <- pivoted |> 
  dplyr::select(npi:state) |> 
  dplyr::mutate(address = campfin::normal_address(address)) |>
  tidyr::unite("address", address:state, remove = TRUE, sep = " ") |> 
  dplyr::distinct(address, .keep_all = TRUE)

# Geocode with {tidygeocoder}
rhc_coords <- tidygeocoder::geocode(clean, 
                                    address = address, 
                                    method = "mapbox", 
                                    full_results = TRUE, 
                                    unique_only = FALSE) |> 
  dplyr::select(npi, organization, purpose, place_name, lat, long)

# Join & convert lat/long columns to `{sf}` geometry <POINT> object
rhc_sf_points <- dplyr::left_join(pivoted, rhc_coords, 
                 relationship = "many-to-many", 
                 by = dplyr::join_by(npi, organization, purpose)) |> 
  dplyr::select(-c(zip, place_name)) |> 
  dplyr::rename(zip = zipnorm) |> 
  sf::st_as_sf(coords = c("lat", "long"))

# ----------------------------------------------
# `{zipcodeR}`: Retrieve Counties from Zip codes 
zip_db <- dplyr::tibble(zip_code_db) |> 
  dplyr::filter(state == "GA" | state == "FL") |> 
  dplyr::select(
    zipcode, 
    city = major_city, 
    county, 
    state, 
    lat, 
    lng, 
    pop_total = population, 
    pop_dense = population_density,
    med_income = median_household_income,
    dplyr::contains("bounds"))

# Join RHCs to Counties
rhc_zip <- dplyr::left_join(
  pivoted, 
  zip_db, 
  by = dplyr::join_by(state, zipnorm == zipcode))

# Create data frame of unique state/county pairs
# Remove "County" from county names
st_cnty <- rhc_zip |> 
  distinct(state, county) |> 
  mutate(county = stringr::str_remove(county, " County"))

# Make separate, equal-length lists of the states and counties
x <- list(st_cnty$state)
y <- list(st_cnty$county)

# Retrieve county FIPS codes
# Retrieve geometries based on county FIPS
z    <- purrr::map2(x, y, fipio::as_fips)
z_sf <- purrr::map(z, fipio::fips_geometry) |> purrr::list_rbind()
z_sf[[1]]

# Unlist & insert into new tibble with geometry
st_ct_fips <- dplyr::tibble(
  state = unlist(x),
  county = unlist(y),
  fips = unlist(z),
  geometry = z_sf[[1]])


# Create `{sf}` <MULTIPOLYGON> object
counties_sf <- sf::st_as_sf(st_ct_fips)
counties_sf

# -----------------------------------------------------
sf::st_crs(counties_sf)$epsg
sf::st_crs("EPSG:4326")$epsg
sf::st_crs(ga_base_map)$epsg

sf::st_crs(rhc_sf_points)$epsg

rhc_sf_points_4326 <- sf::st_transform(rhc_sf_points, 4326)

ga_base_map <- USA.state.boundaries::state_boundaries_wgs84 |> 
  dplyr::filter(STATE_ABBR == "GA")
fl_base_map <- USA.state.boundaries::state_boundaries_wgs84 |> 
  dplyr::filter(STATE_ABBR == "FL")

# -----------------------------------------------------------------------------
ggplot2::ggplot() +
  ggplot2::geom_sf(data = ga_base_map, 
                   fill = "white", 
                   linewidth = 0.25) +
  ggplot2::geom_sf(data = fl_base_map, 
                   fill = "white", 
                   linewidth = 0.25) +
  ggplot2::geom_sf(data = counties_sf, 
                   fill = "darkgreen", 
                   alpha = 0.3, 
                   color = "white", 
                   linewidth = 0.75) +
  ggplot2::geom_point(data = rhc_coords, 
                      ggplot2::aes(long, lat),
                      fill = "orange",
                      color = "darkred", 
                      alpha = 1, 
                      size = 2, 
                      shape = 21,
                      stroke = 1.5) +
  # ggplot2::geom_sf_text(data = rhc_sf_points_4326, 
             # ggplot2::aes(geometry = geometry, label = tx_desc)) +
  # ggplot2::coord_sf(crs = count_crs) +
  ggplot2::theme_void()
```

