---
title: "provider for Analysis"
description: "Demographics, Patient Mix, and Performance"
author: "Andrew Bruce"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse  = FALSE,
  echo      = TRUE, 
  message   = FALSE, 
  warning   = FALSE,
  error     = TRUE,
  comment   = "#>",
  dpi       = 600, 
  out.width = "100%",
  fig.path  = "man/figures/README-"
)
options(scipen = 999)
```

```{r message=FALSE, warning=FALSE}
library(provider)
library(tidyverse)
library(gt)
```

<br>

```{r}
val <- map_dfr(pop_years(), ~by_provider(year = .x, city = "Valdosta", state = "GA"))
```

<br>

```{r}
val |> 
  group_by(year) |> 
  summarise(
    provs = n(),
    hcpcs = sum(tot_hcpcs),
    benes = sum(tot_benes),
    srvcs = sum(tot_srvcs)) |> 
  change(!c('year')) |> 
  ror(provs) |> 
  ror(hcpcs) |> 
  ror(benes) |> 
  ror(srvcs) |> 
  select(year,
         provs,
         provs_chg,
         provs_ror,
         provs_pct,
         hcpcs,
         hcpcs_chg,
         hcpcs_ror,
         hcpcs_pct,
         benes,
         benes_chg,
         benes_ror,
         benes_pct,
         srvcs,
         srvcs_chg,
         srvcs_ror,
         srvcs_pct) |> 
  gt(rowname_col = "year") |> 
  sub_zero(zero_text = "") |> 
  sub_missing(missing_text = "") |>
  fmt_integer(columns = c(provs, hcpcs, benes, srvcs), sep_mark = ",") |>
  fmt_integer(columns = ends_with("chg"), force_sign = TRUE) |>
  fmt_percent(columns = ends_with("ror")) |>
  fmt_percent(columns = ends_with("pct"), force_sign = TRUE) |>
  cols_label(
    provs = "Tot",
    provs_chg = "Abs",
    provs_ror = "RoR",
    provs_pct = "%",
    hcpcs = "Tot",
    hcpcs_chg = "Abs",
    hcpcs_ror = "RoR",
    hcpcs_pct = "%",
    benes = "Tot",
    benes_chg = "Abs",
    benes_ror = "RoR",
    benes_pct = "%",
    srvcs = "Tot",
    srvcs_chg = "Abs",
    srvcs_ror = "RoR",
    srvcs_pct = "%") |> 
  tab_spanner(label = "Providers",
    columns = c(provs, provs_chg, provs_ror, provs_pct)) |> 
  tab_spanner(label = "HCPCS",
    columns = c(hcpcs, hcpcs_chg, hcpcs_ror, hcpcs_pct)) |>
  tab_spanner(label = "Beneficiaries",
    columns = c(benes, benes_chg, benes_ror, benes_pct)) |>
  tab_spanner(label = "Services",
    columns = c(srvcs, srvcs_chg, srvcs_ror, srvcs_pct)) |>
  opt_table_font(font = google_font(name = "JetBrains Mono")) |> 
  opt_all_caps() |> 
  opt_stylize(color = "gray")
```

<br><br>


## Provider Utilization Summary

```{r}
ind <- map_dfr(pop_years(), ~by_provider(year = .x, npi = 1043245657))
# ind <- map_dfr(pop_years(), ~by_provider(year = .x, npi = 1023076643))
```

<br>


Beneficiary Demographics

```{r}
check_xmark <- function(gt_tbl, cols) {

  gt_tbl |>
    gt::text_case_when(
      x == TRUE ~ gt::html(
        fontawesome::fa("check",
                        prefer_type = "solid",
                        fill = "black")),
      x == FALSE ~ gt::html(
        fontawesome::fa("xmark",
                        prefer_type = "solid",
                        fill = "red")),
      .default = NA,
      .locations = gt::cells_body(
        columns = {{ cols }}))
}

select(ind, year, tot_benes, demographics) |> 
  unnest(demographics) |>
  select(-contains("race")) |>
  mutate(across(c(bene_age_lt65:bene_ndual), \(x) coalesce(x, 0))) |> 
  rowwise() |>
  mutate(tot_bene_age = sum(c_across(bene_age_lt65:bene_age_gt84), na.rm = TRUE), 
         tot_bene_gen = sum(c_across(bene_gen_female:bene_gen_male), na.rm = TRUE), 
         tot_bene_dual = sum(c_across(bene_dual:bene_ndual), na.rm = TRUE),
         tot_age_eq = if_else(tot_benes == tot_bene_age, TRUE, FALSE),
         tot_gen_eq = if_else(tot_benes == tot_bene_gen, TRUE, FALSE),
         tot_dual_eq = if_else(tot_benes == tot_bene_dual, TRUE, FALSE),
         verdict = if_else(isTRUE(tot_age_eq) && isTRUE(tot_gen_eq) && isTRUE(tot_dual_eq), TRUE, FALSE),
         .after = tot_benes) |> 
  select(year, 
         tot_benes, 
         tot_bene_age, 
         tot_age_eq, 
         tot_bene_gen, 
         tot_gen_eq, 
         tot_bene_dual, 
         tot_dual_eq, 
         verdict, 
         bene_age_avg:bene_ndual) |>
  # filter(verdict ==TRUE) |> 
  gt(rowname_col = "year") |> 
  cols_label(
    tot_benes = "Total",
    tot_bene_age = "A",
    tot_age_eq = "",
    tot_bene_gen = "G",
    tot_gen_eq = "",
    tot_bene_dual = "D",
    tot_dual_eq = "",
    bene_age_avg = "Avg",
    bene_age_lt65 = "<65", 
    bene_age_65_74 = "65-74", 
    bene_age_75_84 = "75-84", 
    bene_age_gt84 = ">84",
    bene_gen_male = "M", 
    bene_gen_female = "F",
    bene_dual = "1", 
    bene_ndual = "2") |> 
  tab_spanner(label = "Age", columns = c(bene_age_lt65, bene_age_65_74, bene_age_75_84, bene_age_gt84)) |> 
  tab_spanner(label = "Gender", columns = c(bene_gen_male, bene_gen_female)) |> 
  tab_spanner(label = "Dual Status", columns = c(bene_dual, bene_ndual)) |> 
  opt_table_font(font = google_font(name = "JetBrains Mono")) |> 
  sub_missing(missing_text = "") |>
  sub_zero(zero_text = "") |>
  opt_all_caps() |> 
  check_xmark(cols = c(tot_age_eq, tot_gen_eq, tot_dual_eq, verdict)) |> 
  opt_stylize(color = "gray")
```

<br><br>

__Beneficiary Health data__

_`rowwise()`/`c_across()` function to calculate actual number of beneficiaries, e.g. tot_benes * cc_af_

```{r}
select(ind, year, tot_benes, conditions) |> 
  unnest(conditions) |>
  gt(rowname_col = "year") |> 
  cols_label(tot_benes = "Total") |>  
  fmt_percent(columns = starts_with("cc_"), decimals = 0) |>
  opt_table_font(font = google_font(name = "JetBrains Mono")) |> 
  sub_missing(missing_text = "") |>
  sub_zero(zero_text = "") |>
  opt_all_caps()
```

<br><br>

```{r}
select(ind, year, starts_with("tot_")) |> 
  select(-tot_hcpcs, -tot_std_pymt) |> 
  change(starts_with("tot_")) |> 
  select(-ends_with("_cum")) |> 
  gt(rowname_col = "year") |> 
  fmt_integer(columns = c(tot_benes, 
                          tot_srvcs, 
                          tot_benes_chg, 
                          tot_srvcs_chg, 
                          tot_charges_chg, 
                          tot_allowed_chg, 
                          tot_payment_chg), suffixing = TRUE) |> 
  fmt_currency(columns = c(tot_charges, 
                           tot_allowed, 
                           tot_payment), decimals = 0, suffixing = TRUE) |> 
  fmt_percent(columns = contains("pct"), decimals = 0, force_sign = TRUE) |>
  sub_zero(zero_text = "") |> 
  grand_summary_rows(columns = c(tot_benes_chg, 
                                 tot_srvcs_chg,
                                 tot_charges_chg, 
                                 tot_allowed_chg, 
                                 tot_payment_chg),
                     fns =  list(label = md("**Sum**"), 
                                 id = "sum", fn = "sum"),
                     fmt = ~ fmt_integer(., suffixing = TRUE), 
                     missing_text = "") |> 
  grand_summary_rows(columns = c(tot_benes_pct,
                                 tot_srvcs_pct,
                                 tot_charges_pct, 
                                 tot_allowed_pct, 
                                 tot_payment_pct),
                     fns =  list(label = md("**Sum**"), 
                                 id = "sum", fn = "sum"),
                     fmt = ~ fmt_percent(., decimals = 0, force_sign = TRUE), 
                     missing_text = "") |> 
  tab_spanner(label = "Beneficiaries",columns = contains("bene")) |> 
  tab_spanner(label = "Services", columns = contains("srvcs")) |> 
  tab_spanner(label = "Charges", columns = contains("charges")) |> 
  tab_spanner(label = "Allowed", columns = contains("allowed")) |> 
  tab_spanner(label = "Payment", columns = contains("payment")) |> 
  cols_label(
    tot_benes       = ("Tot"),
    tot_benes_chg   = ("YoY"),
    tot_benes_pct   = ("(%)"),
    tot_srvcs       = ("Tot"),
    tot_srvcs_chg   = ("YoY"),
    tot_srvcs_pct   = ("(%)"),
    tot_charges     = ("Tot"),
    tot_charges_chg = ("YoY"),
    tot_charges_pct = ("(%)"),
    tot_allowed     = ("Tot"),
    tot_allowed_chg = ("YoY"),
    tot_allowed_pct = ("(%)"),
    tot_payment     = ("Tot"),
    tot_payment_chg = ("YoY"),
    tot_payment_pct = ("(%)")) |> 
  cols_hide(columns = ends_with("_chg")) |> 
  opt_table_font(font = google_font(name = "JetBrains Mono")) |>
  tab_header(title = md("**Medicare Part B** Utilization"),
             subtitle = md("Counts & Amounts, 2013-2019")) |> 
  data_color(columns = c(tot_benes, tot_srvcs, tot_charges, tot_allowed, tot_payment),
             method = "numeric",
             palette = "Reds") |> 
  data_color(columns = c(tot_benes_chg, tot_benes_pct),
             rows = tot_benes_chg < 0,
             method = "numeric",
             palette = "red2", 
             apply_to = "text") |> 
  data_color(columns = c(tot_benes_chg, tot_benes_pct),
             rows = tot_benes_chg > 0,
             method = "numeric",
             palette = "gray90", 
             apply_to = "fill") |> 
  data_color(columns = c(tot_srvcs_chg, tot_srvcs_pct),
             rows = tot_srvcs_chg < 0,
             method = "numeric",
             palette = "red2", 
             apply_to = "text") |> 
  data_color(columns = c(tot_srvcs_chg, tot_srvcs_pct),
             rows = tot_srvcs_chg > 0,
             method = "numeric",
             palette = "gray90", 
             apply_to = "fill") |> 
  data_color(columns = c(tot_charges_chg, tot_charges_pct),
             rows = tot_charges_chg < 0,
             method = "numeric",
             palette = "red2", 
             apply_to = "text") |> 
  data_color(columns = c(tot_charges_chg, tot_charges_pct),
             rows = tot_charges_chg > 0,
             method = "numeric",
             palette = "gray90", 
             apply_to = "fill") |> 
  data_color(columns = c(tot_allowed_chg, tot_allowed_pct),
             rows = tot_allowed_chg < 0,
             method = "numeric",
             palette = "red2", 
             apply_to = "text") |> 
  data_color(columns = c(tot_allowed_chg, tot_allowed_pct),
             rows = tot_allowed_chg > 0,
             method = "numeric",
             palette = "gray90", 
             apply_to = "fill") |> 
  data_color(columns = c(tot_payment_chg, tot_payment_pct),
             rows = tot_payment_chg < 0,
             method = "numeric",
             palette = "red2", 
             apply_to = "text") |> 
  data_color(columns = c(tot_payment_chg, tot_payment_pct),
             rows = tot_payment_chg > 0,
             method = "numeric",
             palette = "gray90", 
             apply_to = "fill") |> 
  tab_options(table.width = pct(100),
              column_labels.font.weight = "bold",
              row_group.font.weight = "bold",
              heading.background.color = "black",
              heading.align = "left") |> 
  opt_all_caps()
```

<br><br>

```{r}
select(ind, 
       year, 
       Beneficiaries = tot_benes,
       Services = tot_srvcs,
       Charges = tot_charges,
       Allowed = tot_allowed,
       Payment = tot_payment) |> 
  pivot_longer(cols = c(Beneficiaries, 
                        Services, 
                        Charges, 
                        Allowed, 
                        Payment), 
               names_to = "Type", 
               values_to = "Amount") |> 
  pivot_wider(names_from = year, 
              values_from = Amount) |> 
  gt(rowname_col = "Type") |> 
  cols_hide(columns = contains("20")) |>
  cols_nanoplot(
    columns = contains("20"),
    new_col_name = "nanoplots",
    new_col_label = md("*TREND*"),
    reference_line = "mean",
    plot_height = "3em",
    options = nanoplot_options(
      data_line_stroke_color = "black",
      show_reference_line = TRUE,
      show_reference_area = FALSE)) |> 
  opt_table_font(font = google_font(name = "JetBrains Mono")) |>
  tab_header(title = md("**Medicare Part B** Utilization"),
             subtitle = md("Trends, 2014-2021")) |> 
  opt_horizontal_padding(scale = 2) |> 
  tab_options(table.width = pct(75),
              column_labels.font.weight = "bold",
              row_group.font.weight = "bold",
              heading.background.color = "black",
              heading.align = "left")
```

<br>

### Chronic Condition Prevalence

```{r}
chronic1 <- compare_conditions(ind, pivot = FALSE)
chronic2 <- compare_conditions(ind, pivot = TRUE)
```

<br>

```{r}
chronic1 |>
  # filter(prevalence > 0)
  # filter(!if_any(contains("20"), ~ . <= 0)) |>
  pivot_wider(names_from = year, 
              values_from = prevalence) |>
  gt(rowname_col = "level") |> 
  fmt_percent(columns = contains('0'), decimals = 0) |>
  opt_table_font(font = google_font(name = "JetBrains Mono")) |> 
  sub_missing(missing_text = "") |> 
  cols_nanoplot(
    columns = starts_with("20"),
    plot_type = "bar",
    new_col_name = "change",
    new_col_label = "change",
    missing_vals = "remove",
    options = nanoplot_options(
      show_data_line = FALSE,
      show_data_area = FALSE,
      data_bar_stroke_color = "transparent"
    )
  )
```

<br><br>

```{r}
chronic2 |>
  gt() |> 
  tab_spanner_delim(delim = "_") |>
  # gt_preview(top_n = 20) |> 
  fmt_percent(columns = starts_with("20"), decimals = 0) |>
  opt_table_font(font = google_font(name = "JetBrains Mono")) |> 
  sub_missing(missing_text = "-")
```

<br><br>


```{r}
gt(chronic2) |> 
  cols_nanoplot(
    columns = contains("Provider"),
    reference_line = "mean",
    new_col_name = "provider_plot",
    new_col_label = md("*Provider*"),
    missing_vals = "zero",
    plot_height = "3em",
    options = nanoplot_options(
      data_line_stroke_color = "black",
      show_reference_line = TRUE,
      show_reference_area = FALSE)) |> 
  cols_nanoplot(
    columns = contains("State"),
    reference_line = "mean",
    new_col_name = "state_plot",
    new_col_label = md("*State*"),
    missing_vals = "zero",
    plot_height = "3em",
    options = nanoplot_options(
      data_line_stroke_color = "black",
      show_reference_line = TRUE,
      show_reference_area = FALSE)) |> 
  cols_nanoplot(
    columns = contains("National"),
    reference_line = "mean",
    new_col_name = "national_plot",
    new_col_label = md("*National*"),
    missing_vals = "zero",
    plot_height = "3em",
    options = nanoplot_options(
      data_line_stroke_color = "black",
      show_reference_line = TRUE,
      show_reference_area = FALSE)) |> 
  cols_hide(columns = contains("20")) |>
  opt_table_font(font = google_font(name = "JetBrains Mono")) |>
  tab_header(title = md("**Medicare Part B** Utilization"),
             subtitle = md("**Chronic Conditions Prevalence** Comparison, 2013-2018")) |> 
  opt_horizontal_padding(scale = 2) |> 
  tab_options(table.width = pct(50),
              column_labels.font.weight = "bold",
              row_group.font.weight = "bold",
              heading.background.color = "black",
              heading.align = "left")
```


<br>
<br>


```{r}
gt(chronic2) |> 
  cols_nanoplot(
    columns = contains("Provider"),
    plot_type = "bar",
    new_col_name = "provider_plot",
    new_col_label = md("*Provider*"),
    missing_vals = "remove",
    plot_height = "3em",
    options = nanoplot_options(
      data_bar_stroke_color = "GoldenRod",
      data_bar_fill_color = "DarkOrange")) |> 
  cols_nanoplot(
    columns = contains("State"),
    plot_type = "bar",
    new_col_name = "state_plot",
    new_col_label = md("*State*"),
    missing_vals = "remove",
    plot_height = "3em",
    options = nanoplot_options(
      data_bar_stroke_color = "GoldenRod",
      data_bar_fill_color = "DarkOrange")) |> 
  cols_nanoplot(
    columns = contains("National"),
    plot_type = "bar",
    new_col_name = "nat_plot",
    new_col_label = md("*National*"),
    missing_vals = "remove",
    plot_height = "3em",
    options = nanoplot_options(
      data_bar_stroke_color = "GoldenRod",
      data_bar_fill_color = "DarkOrange")) |> 
  cols_hide(columns = contains("20")) |>
  opt_table_font(font = google_font(name = "JetBrains Mono")) |>
  tab_header(title = md("**Medicare Part B** Utilization"),
             subtitle = md("**Chronic Conditions Prevalence** Comparison, 2013-2018")) |> 
  opt_horizontal_padding(scale = 2) |> 
  tab_options(table.width = pct(50),
              column_labels.font.weight = "bold",
              row_group.font.weight = "bold",
              heading.background.color = "black",
              heading.align = "left")
```

<br>
<br>

## HCPCS Utilization Data

```{r}
srvc <- map_dfr(pop_years(), ~by_service(year = .x, npi = 1023076643))
```

<br>

```{r}
srvc |> 
  select(year, 
         hcpcs_code, 
         family, 
         tot_benes, 
         tot_srvcs, 
         avg_charge, 
         avg_allowed, 
         avg_payment) |> 
  group_by(year, family) |> 
  summarise(tot_benes = sum(tot_benes),
            tot_srvcs = sum(tot_srvcs),
            avg_charge = mean(avg_charge), 
            avg_allowed = mean(avg_allowed), 
            avg_payment = mean(avg_payment), .groups = "drop") |>
  arrange(family) |> 
  gt(rowname_col = "year") |> 
  fmt_currency(columns = starts_with("avg_"), decimals = 0) |>
  cols_label(
    tot_benes = "Beneficiaries",
    tot_srvcs = "Services",
    avg_charge = "Charge",
    avg_allowed= "Allowed",
    avg_payment = "Payment") |> 
  opt_table_font(font = google_font(name = "JetBrains Mono")) |> 
  opt_all_caps()
```

<br>
<br>


```{r}
hcpcs <- compare_hcpcs(srvc)

hcpcs |> 
  select(year, 
         level,
         hcpcs_code,
         category,
         subcategory,
         family, 
         beneficiaries, 
         services, 
         avg_charge, 
         avg_allowed, 
         avg_payment) |> 
  arrange(hcpcs_code, year) |>
  gt(rowname_col = "year") |> 
  cols_label(
    hcpcs_code = "HCPCS",
    avg_charge = "Charge",
    avg_allowed= "Allowed",
    avg_payment = "Payment") |> 
  cols_align(columns = "level", align = "left") |>
  fmt_integer(columns = c(beneficiaries, services)) |>
  fmt_currency(columns = starts_with("avg_"), decimals = 0) |>
  opt_table_font(font = google_font(name = "JetBrains Mono")) |> 
  opt_all_caps()
```



<br>
<br>

```{r}
hcpcs |> 
  group_by(year, level, category) |>
  summarise(Beneficiaries = sum(beneficiaries),
            Services = sum(services),
            "Average Payment" = mean(avg_payment), .groups = "drop") |>
  arrange(year, category) |>
  gt(rowname_col = "year") |> 
  cols_align("left", level) |> 
  cols_move_to_start(columns = category) |> 
  fmt_integer(columns = c(Beneficiaries, Services)) |> 
  fmt_currency(columns = c('Average Payment'), decimals = 2) |> 
  opt_table_font(font = google_font(name = "JetBrains Mono")) |>
  tab_header(title = md("**Medicare Part B** Utilization")) |> 
  opt_horizontal_padding(scale = 2) |> 
  tab_options(table.width = pct(50),
              column_labels.font.weight = "bold",
              row_group.font.weight = "bold",
              heading.background.color = "black",
              heading.align = "left") |> 
  opt_all_caps()
```

<br><br>

```{r}
# hcpcs |>
# select(year, 
#          level, 
#          HCPCS = hcpcs_code,
#          beneficiaries,
#          services, 
#          "Average Payment" = avg_payment) |> 
#   mutate("Services Per Beneficiary" = services/beneficiaries) |> 
#   select(-c(beneficiaries, services)) |> 
#   pivot_longer(!year:HCPCS, 
#                names_to = "stat", 
#                values_to = "amount") |> 
#   pivot_wider(names_from = level, 
#               values_from = amount) |> 
#   arrange(stat, HCPCS) |> 
#   filter(stat %in% c("Services Per Beneficiary")) |> 
#   gt(rowname_col = "year") |> 
#   fmt_number(columns = c(Provider, State, National), decimals = 2) |> 
#   opt_table_font(font = google_font(name = "JetBrains Mono")) |>
#   tab_header(title = md("**Services Per Beneficiary** By HCPCS")) |> 
#   cols_hide(stat) |> 
#   data_color(columns = c(Provider, State, National),
#              direction = "row",
#              method = "numeric",
#              palette = "Reds") |> 
#   tab_options(table.width = pct(75),
#               column_labels.font.weight = "bold",
#               row_group.font.weight = "bold",
#               heading.background.color = "black",
#               heading.align = "left")
```

<br>
