---
title: "Pending Applications"
output: html_document
---

```{r include = FALSE}
knitr::opts_chunk$set(
  collapse  = TRUE,
  echo      = TRUE, 
  message   = TRUE, 
  warning   = FALSE,
  error     = TRUE,
  comment   = "#>",
  dpi       = 300, 
  out.width = "100%",
  fig.path  = "man/figures/README-"
)
```

```{r setup}
library(provider)
```

<br>

The Pending Initial Logging and Tracking (L & T) dataset provides a list of pending applications that have not been processed by CMS contractors.

<br>

## Search Examples

```{r}
pending_applications(last_name = "Smith", 
                     type = "physician") |> 
  provider:::gt_prov()
```

<br>

```{r}
pending_applications(last_name = "Bruce", 
                     type = "non-physician") |> 
  provider:::gt_prov()
```

<br>


### Links

   * [Medicare Pending Initial Logging and Tracking Physicians API](https://data.cms.gov/provider-characteristics/medicare-provider-supplier-enrollment/pending-initial-logging-and-tracking-physicians)
   * [Medicare Pending Initial Logging and Tracking Non-Physicians API](https://data.cms.gov/provider-characteristics/medicare-provider-supplier-enrollment/pending-initial-logging-and-tracking-non-physicians)
