---
title: "Physician by Provider"
output: html_document
---

```{r include = FALSE}
knitr::opts_chunk$set(
  collapse  = TRUE,
  echo      = TRUE, 
  message   = FALSE, 
  warning   = FALSE,
  error     = TRUE,
  comment   = "#>",
  dpi       = 300, 
  out.width = "100%",
  fig.path  = "man/figures/README-"
)
library(printr)
```

```{r message=FALSE, warning=FALSE}
library(provider)
library(tidyverse)
```


### Medicare Utilization Summary

```{r}
df <- by_provider_years() |> 
  map(\(x) by_provider(year = x, npi = 1023076643)) |> 
  list_rbind()
```

```{r eval=FALSE, echo=FALSE}
hcc_dual <- df$year |> 
  map(\(x) quality_stats(year = x)) |> 
  list_rbind() |> 
  filter(!is.na(value), type == "Individual") |> 
  pivot_wider(names_from = "stat", values_from = "value") |> 
  janitor::clean_names() |> 
  select(year, 
         hcc_risk_avg_nat = hcc_risk_score_average, 
         dual_eligibility_ratio_avg = dual_eligibility_average)

select(df, year, demographics) |> 
  unnest(demographics) |> 
  #janitor::remove_empty(which = c("rows", "cols")) |> 
  mutate(dual_eligibility_ratio = bene_dual / bene_ndual) |> 
  left_join(select(hcc_dual, -hcc_risk_avg_nat), by = join_by(year)) |> 
  select(year, contains(c("age", "male", "elig")))
```


### Counts & Amounts

```{r}
select(df, year, tot_hcpcs:tot_payment)
```

### Chronic Condition Prevalence

```{r}
chronic <- compare_conditions(df)
chronic |> 
  pivot_wider(names_from = level, values_from = prevalence) |> 
  arrange(condition) |> 
  gt::gt(groupname_col = "condition") |> 
  gt::fmt_percent(columns = c(Provider, State, National)) |> 
  gtExtras::gt_theme_nytimes()
```


## HCPCS Utilization Data

```{r}
hcpcs <- by_service_years() |> 
  map(\(x) by_service(year = x, npi = 1023076643)) |> 
  list_rbind() |> 
  compare_hcpcs()
```

<br>

```{r}
table <- hcpcs |> 
  select(year, 
         level, 
         hcpcs_code,
         BENEFICIARIES = beneficiaries,
         SERVICES = services, 
         "Average Charge" = avg_charge, 
         "Average Allowed" = avg_allowed, 
         "Average Payment" = avg_payment) |> 
  pivot_longer(!year:hcpcs_code, 
               names_to = "stat", 
               values_to = "amount") |> 
  pivot_wider(names_from = level, 
              values_from = amount)

# TODO: AVG PROCEDURES PER BENEFICIARY
table |> 
  filter(stat %in% c("SERVICES")) |> 
  arrange(stat, hcpcs_code) |> 
  gt::gt(groupname_col = "stat", rowname_col = "hcpcs_code") |> 
  gt::fmt_number(decimals = 0) |> 
  gt::fmt_integer(columns = "year", sep_mark = "") |> 
  gt::cols_label(hcpcs_code = "HCPCS") |> 
  gtExtras::gt_theme_nytimes()

table |> 
  filter(stat %in% c("BENEFICIARIES")) |> 
  arrange(stat, hcpcs_code) |> 
  gt::gt(groupname_col = "stat", rowname_col = "hcpcs_code") |> 
  gt::fmt_number(decimals = 0) |> 
  gt::fmt_integer(columns = "year", sep_mark = "") |> 
  gt::cols_label(hcpcs_code = "HCPCS") |> 
  gtExtras::gt_theme_nytimes()

table |> 
  filter(stat %in% c("Average Payment")) |> 
  arrange(stat, hcpcs_code) |> 
  gt::gt(groupname_col = "stat", rowname_col = "hcpcs_code") |> 
  gt::fmt_number(decimals = 2) |> 
  gt::fmt_integer(columns = "year", sep_mark = "") |> 
  #gt::cols_label(hcpcs_code = "HCPCS") |> 
  gtExtras::gt_theme_nytimes()
```

