# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  # <laboratories>
  "a2la",
  # <laboratories>
  "aabb",
  # <laboratories>
  "accredited",
  # <laboratories>
  "acr_a2la",
  # <laboratories>
  "acr_a2la_date",
  # <laboratories>
  "acr_a2la_ind",
  # <laboratories>
  "acr_aabb",
  # <laboratories>
  "acr_aabb_date",
  # <laboratories>
  "acr_aabb_ind",
  # <laboratories>
  "acr_aoa",
  # <laboratories>
  "acr_aoa_date",
  # <laboratories>
  "acr_aoa_ind",
  # <laboratories>
  "acr_ashi",
  # <laboratories>
  "acr_ashi_date",
  # <laboratories>
  "acr_ashi_ind",
  # <laboratories>
  "acr_cap",
  # <laboratories>
  "acr_cap_date",
  # <laboratories>
  "acr_cap_ind",
  # <laboratories>
  "acr_cola",
  # <laboratories>
  "acr_cola_date",
  # <laboratories>
  "acr_cola_ind",
  # <laboratories>
  "acr_jcaho",
  # <laboratories>
  "acr_jcaho_date",
  # <laboratories>
  "acr_jcaho_ind",
  # <hospitals>
  # <laboratories>
  # <nppes>
  "address",
  # <nppes>
  "addresses",
  # <laboratories>
  "aoa",
  # <encode_param>
  "arg",
  # <laboratories>
  "ashi",
  # <nppes>
  "basic",
  # <laboratories>
  "cap",
  # <tidyup>
  "clean_credentials",
  # <tidyup>
  "clean_dollars",
  # <laboratories>
  "clia_number",
  # <laboratories>
  "cmplnc_stus_cd",
  # <laboratories>
  "cola",
  # <laboratories>
  "confirmed",
  # <laboratories>
  "confirmed_date",
  # <laboratories>
  "crtfct_type_cd",
  # <laboratories>
  "crtfctn_actn_type_cd",
  # <laboratories>
  "current_clia_lab_clsfctn_cd",
  # <cms_dataset_search>
  "description",
  # <cms_update>
  "distribution",
  # <cms_update>
  "distribution_accessURL",
  # <cms_update>
  "distribution_format",
  # <cms_update>
  "distribution_modified",
  # <cms_update>
  "distribution_title",
  # <laboratories>
  "duration",
  # <order_refer>
  "eligible",
  # <nppes>
  "entity_type",
  # <nppes>
  "ep",
  # <hospitals>
  "flag",
  # <nppes>
  "gender",
  # <laboratories>
  "gnrl_cntl_type_cd",
  # <laboratories>
  "gnrl_fac_type_cd",
  # <reassignments>
  "group_state_code",
  # <cms_update>
  # <nppes>
  "id",
  # <cms_dataset_search>
  "identifier",
  # <hospitals>
  "incorp_state",
  # <reassignments>
  "individual_state_code",
  # <laboratories>
  "jcaho",
  # <cms_dataset_search>
  "keyword",
  # <hospitals>
  "location_type",
  # <cms_update>
  # <cms_dataset_search>
  "modified",
  # <tidyup>
  "na_blank",
  # <nppes>
  "on",
  # <laboratories>
  "organization",
  # <laboratories>
  "pgm_trmntn_cd",
  # <nppes>
  "pr",
  # <hospitals>
  "proprietary_nonprofit",
  # <laboratories>
  "provider_name",
  # <laboratories>
  "prvdr_ctgry_cd",
  # <laboratories>
  "prvdr_ctgry_sbtyp_cd",
  # <nppes>
  "purpose",
  # <reassignments>
  "record_type",
  # <laboratories>
  "rgn_cd",
  # <fct_stabb>
  # <state_recode>
  # <abb2full>
  "state.abb",
  # <fct_stname>
  # <state_recode>
  # <abb2full>
  "state.name",
  # <laboratories>
  "state_cd",
  # <opt_out>
  "state_code",
  # <nppes>
  # <order_refer>
  "status",
  # <hospitals>
  "subgroup_general",
  # <hospitals>
  "subgroup_other",
  # <hospitals>
  "subtotal",
  # <cms_update>
  # <cms_dataset_search>
  # <api_provider>
  # <api_medicare>
  "title",
  # <laboratories>
  "trmntn_exprtn_dt",
  # <nppes>
  "tx",
  # <laboratories>
  "type_of_action",
  # <abb2full>
  "x",
  # <hospitals>
  # <laboratories>
  # <nppes>
  # <opt_out>
  # <order_refer>
  # <pending>
  # <reassignments>
  # <abb2full>
  "y",
  # <cms_update>
  "year",
  NULL
))
