# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "Year", # <cc_multiple>
  "Year", # <cc_specific>
  "title", # <cms_update_ids>
  "modified", # <cms_update_ids>
  "distribution", # <cms_update_ids>
  "distribution_format", # <cms_update_ids>
  "distribution_title", # <cms_update_ids>
  "distribution_modified", # <cms_update_ids>
  "distribution_accessURL", # <cms_update_ids>
  "data_lists", # <nppes_npi>
  "outcome", # <nppes_npi>
  "description", # <nppes_npi>
  "field", # <nppes_npi>
  "number", # <nppes_npi>
  "created_epoch", # <nppes_npi>
  "last_updated_epoch", # <nppes_npi>
  "enumeration_type", # <nppes_npi>
  "basic", # <nppes_npi>
  "basic_organization_name", # <nppes_npi>
  "addresses", # <nppes_npi>
  "basic_first_name", # <nppes_npi>
  "basic_last_name", # <nppes_npi>
  "record_id", # <open_payments>
  "program_year", # <open_payments>
  "record_number", # <open_payments>
  "title", # <open_payments_update_ids>
  "modified", # <open_payments_update_ids>
  "distribution", # <open_payments_update_ids>
  "data", # <open_payments_update_ids>
  "identifier", # <open_payments_update_ids>
  "NPI", # <opt_out>
  "Date", # <opt_out>
  "PARTB", # <order_refer>
  "HHA", # <order_refer>
  "DME", # <order_refer>
  "PMD", # <order_refer>
  "Year", # <physician_by_geography>
  "Year", # <physician_by_provider>
  "Year", # <physician_by_service>
  ":=", # <age_days>
  "int", # <days_today>
  "secs", # <days_today>
  "mins", # <days_today>
  ":=", # <days_today>
  "hrs", # <days_today>
  ":=", # <re_nest>
  NULL
))
