# 2017      == 17 + ALL
# 2022      == 22 + ALL
# 2023:2024 == 23 + 22 + ALL
#' @noRd
qpp_ALL = list(
  year = "year",
  `practice state or us territory` = "state",
  `practice size` = "size",
  `clinician specialty` = "specialty",
  `years in medicare` = "years",
  npi = "npi",
  `medicare patients` = "patients",
  `allowed charges` = "charges",
  services = "services",
  `opted into mips` = "opted_ind",
  `final score` = "final_score",
  `payment adjustment percentage` = "adjustment",
  `complex patient bonus` = "complex_bonus",
  `quality category score` = "qa_score",
  `promoting interoperability (pi) category score` = "pi_score"
)

#' @noRd
qpp_22 = list(
  `clinician type` = "cred",
  `non-reporting` = "non_report_ind",
  `participation option` = "part_opt",
  `small practice status` = "small_ind",
  `rural status` = "rural_ind",
  `health professional shortage area status` = "hpsa_ind",
  `ambulatory surgical center-based status` = "asc_ind",
  `hospital-based status` = "hospital_ind",
  `non-patient facing status` = "non_patient_ind",
  `facility-based status` = "facility_ind",
  `dual eligibility ratio` = "dual_ratio",
  `safety-net status` = "safety_ind",
  `extreme uncontrollable circumstance (euc)` = "extreme_ind",
  `quality improvement score` = "qi_score",
  `small practice bonus` = "small_bonus",
  `improvement activities (ia) category score` = "ia_score",
  `ia credit` = "ia_credit_ind",
  `cost category score` = "cost_score"
)

#' @noRd
RE_ENROLL = list(
  `ENROLLMENT ID` = "enid",
  NPI = "npi",
  `MULTIPLE NPI FLAG` = "multi",
  CCN = "ccn",
  `ASSOCIATE ID` = "pac",
  `ORGANIZATION NAME` = "org_name",
  `DOING BUSINESS AS NAME` = "org_dba",
  `INCORPORATION DATE` = "inc_date",
  `ORGANIZATION TYPE STRUCTURE` = "org_type",
  `ORGANIZATION OTHER TYPE TEXT` = "org_otxt",
  PROPRIETARY_NONPROFIT = "status",
  `ADDRESS LINE 1` = "address",
  `ADDRESS LINE 2` = "add_2",
  CITY = "city",
  STATE = "state",
  `ZIP CODE` = "zip"
)

#' @noRd
RE_OWNER = list(
  `ENROLLMENT ID` = "org_enid",
  `ASSOCIATE ID` = "org_pac",
  `ORGANIZATION NAME` = "org_name",
  `ASSOCIATE ID - OWNER` = "pac",
  `ROLE TEXT - OWNER` = "role",
  `ASSOCIATION DATE - OWNER` = "asc_date",
  `ORGANIZATION NAME - OWNER` = "own_name",
  `DOING BUSINESS AS NAME - OWNER` = "own_dba",
  `PERCENTAGE OWNERSHIP` = "percent",
  `TITLE - OWNER` = "title",
  `FIRST NAME - OWNER` = "first",
  `MIDDLE NAME - OWNER` = "middle",
  `LAST NAME - OWNER` = "last",
  `ADDRESS LINE 1 - OWNER` = "address",
  `ADDRESS LINE 2 - OWNER` = "add_2",
  `CITY - OWNER` = "city",
  `STATE - OWNER` = "state",
  `ZIP CODE - OWNER` = "zip",
  `CREATED FOR ACQUISITION - OWNER` = "acq_ind",
  `CORPORATION - OWNER` = "corp_ind",
  `LLC - OWNER` = "llc_ind",
  `MEDICAL PROVIDER SUPPLIER - OWNER` = "mps_ind",
  `MANAGEMENT SERVICES COMPANY - OWNER` = "msr_ind",
  `MEDICAL STAFFING COMPANY - OWNER` = "mst_ind",
  `HOLDING COMPANY - OWNER` = "hld_ind",
  `INVESTMENT FIRM - OWNER` = "inv_ind",
  `FINANCIAL INSTITUTION - OWNER` = "fin_ind",
  `CONSULTING FIRM - OWNER` = "con_ind",
  `FOR PROFIT - OWNER` = "fp_ind",
  `NON PROFIT - OWNER` = "np_ind",
  `OTHER TYPE - OWNER` = "oth_ind",
  `OTHER TYPE TEXT - OWNER` = "own_otxt"
)

#' @noRd
RE_OWNER2 = c(
  RE_OWNER,
  `PRIVATE EQUITY COMPANY - OWNER` = "pe_ind",
  `REIT - OWNER` = "reit_ind",
  `CHAIN HOME OFFICE - OWNER` = "cho_ind",
  `OWNED BY ANOTHER ORG OR IND - OWNER` = "ano_ind"
)

#' @noRd
RE_NAME = list(
  affiliations = list(
    provider_first_name = "first",
    # provider_middle_name = "middle",
    provider_last_name = "last",
    npi = "npi",
    ind_pac_id = "pac",
    facility_type = "prov_type",
    facility_affiliations_certification_number = "prov_ccn",
    facility_type_certification_number = "parent_ccn"
  ),
  clia = list(
    FAC_NAME = "fac_name",
    ADDTNL_FAC_NAME = "fac_2",
    PRVDR_NUM = "fac_ccn",
    CLIA_MDCR_NUM = "clia_ccn",
    CHOW_CNT = "chows",
    DRCTLY_AFLTD_LAB_CNT = "labs",
    LAB_SITE_CNT = "sites",
    ST_ADR = "address",
    ADDTNL_ST_ADR = "add_2",
    CITY_NAME = "city",
    STATE_CD = "state",
    ZIP_CD = "zip",
    CLIA_TRMNTN_CD = "term",
    CRTFCT_TYPE_CD = "cert_type",
    GNRL_FAC_TYPE_CD = "fac_type",
    GNRL_CNTL_TYPE_CD = "owner",
    CRTFCTN_ACTN_TYPE_CD = "action",
    CRTFCTN_DT = "cert_date",
    CRTFCT_EFCTV_DT = "eff_date",
    TRMNTN_EXPRTN_DT = "term_date",
    A2LA_ACRDTD_Y_MATCH_DT = "acr_a2la_date",
    AABB_ACRDTD_Y_MATCH_DT = "acr_aabb_date",
    AOA_ACRDTD_Y_MATCH_DT = "acr_aoa_date",
    ASHI_ACRDTD_Y_MATCH_DT = "acr_ashi_date",
    CAP_ACRDTD_Y_MATCH_DT = "acr_cap_date",
    COLA_ACRDTD_Y_MATCH_DT = "acr_cola_date",
    JCAHO_ACRDTD_Y_MATCH_DT = "acr_jcaho_date",
    MLT_SITE_EXCPTN_SW = "site_multi",
    HOSP_LAB_EXCPTN_SW = "hosp_multi",
    NON_PRFT_EXCPTN_SW = "non_multi",
    LAB_TEMP_TSTG_SITE_SW = "tmp_multi",
    ELGBLTY_SW = "elig_ind"
  ),
  clinicians = list(
    provider_first_name = "first",
    # provider_middle_name = "middle",
    provider_last_name = "last",
    gndr = "gender",
    cred = "cred",
    med_sch = "school",
    grd_yr = "grad_year",
    pri_spec = "specialty",
    sec_spec_all = "spec_other",
    npi = "npi",
    ind_pac_id = "pac",
    ind_enrl_id = "enid",
    facility_name = "org_name",
    org_pac_id = "org_pac",
    num_org_mem = "members",
    adr_ln_1 = "address",
    adr_ln_2 = "add_2",
    citytown = "city",
    state = "state",
    zip_code = "zip"
  ),
  dialysis = list(
    cms_certification_number_ccn = "fac_ccn",
    facility_name = "fac_name",
    five_star = "rating",
    network = "network",
    profit_or_nonprofit = "status",
    chain_organization = "chain_name",
    certification_date = "cert_date",
    address_line_1 = "address",
    address_line_2 = "add_2",
    citytown = "city",
    state = "state",
    zip_code = "zip",
    countyparish = "county"
  ),
  hospitals = list(
    `ORGANIZATION NAME` = "org_name",
    `DOING BUSINESS AS NAME` = "org_dba",
    `ENROLLMENT ID` = "enid",
    NPI = "npi",
    `MULTIPLE NPI FLAG` = "multi",
    CCN = "ccn",
    `ASSOCIATE ID` = "pac",
    `INCORPORATION DATE` = "inc_date",
    `ORGANIZATION TYPE STRUCTURE` = "org_type",
    `ORGANIZATION OTHER TYPE TEXT` = "org_otxt",
    `PROPRIETARY NONPROFIT` = "status",
    `ADDRESS LINE 1` = "address",
    `ADDRESS LINE 2` = "add_2",
    CITY = "city",
    STATE = "state",
    `ZIP CODE` = "zip",
    `PRACTICE LOCATION TYPE` = "loc_type",
    `LOCATION OTHER TYPE TEXT` = "loc_otxt",
    `REH CONVERSION DATE` = "reh_date",
    `PROVIDER TYPE CODE` = "prov_type",
    `REH CONVERSION FLAG` = "sub_reh",
    `SUBGROUP - ACUTE CARE` = "sub_acute",
    `SUBGROUP - GENERAL` = "sub_gen",
    `SUBGROUP - SPECIALTY HOSPITAL` = "sub_spec",
    `SUBGROUP - ALCOHOL DRUG` = "sub_adu",
    `SUBGROUP - CHILDRENS` = "sub_child",
    `SUBGROUP - LONG-TERM` = "sub_ltc",
    `SUBGROUP - PSYCHIATRIC` = "sub_psy",
    `SUBGROUP - REHABILITATION` = "sub_irf",
    `SUBGROUP - SHORT-TERM` = "sub_stc",
    `SUBGROUP - SWING-BED APPROVED` = "sub_sba",
    `SUBGROUP - PSYCHIATRIC UNIT` = "sub_psu",
    `SUBGROUP - REHABILITATION UNIT` = "sub_iru",
    `SUBGROUP - OTHER` = "sub_oth",
    `SUBGROUP - OTHER TEXT` = "sg_otxt"
  ),
  hospitals2 = list(
    facility_id = "ccn",
    facility_name = "org_name",
    hospital_type = "prov_type",
    hospital_ownership = "status",
    hospital_overall_rating = "rating",
    address = "address",
    citytown = "city",
    state = "state",
    zip_code = "zip",
    countyparish = "county"
  ),
  opt_out = list(
    NPI = "npi",
    `First Name` = "first",
    `Last Name` = "last",
    Specialty = "specialty",
    `Optout Effective Date` = "start_date",
    `Optout End Date` = "end_date",
    `Last updated` = "updated",
    `First Line Street Address` = "address",
    `Second Line Street Address` = "add_2",
    `City Name` = "city",
    `State Code` = "state",
    `Zip code` = "zip",
    `Eligible to Order and Refer` = "order_refer"
  ),
  order_refer = list(
    FIRST_NAME = "first",
    LAST_NAME = "last",
    NPI = "npi",
    PARTB = "ptb_ind",
    DME = "dme_ind",
    HHA = "hha_ind",
    PMD = "pmd_ind",
    HOSPICE = "hsp_ind"
  ),
  pending = list(
    prov_type = "prov_type",
    FIRST_NAME = "first",
    LAST_NAME = "last",
    NPI = "npi"
  ),
  providers = list(
    ORG_NAME = "org_name",
    FIRST_NAME = "first",
    # MDL_NAME = "middle",
    LAST_NAME = "last",
    STATE_CD = "state",
    PROVIDER_TYPE_CD = "prov_type",
    PROVIDER_TYPE_DESC = "prov_desc",
    NPI = "npi",
    MULTIPLE_NPI_FLAG = "multi",
    PECOS_ASCT_CNTL_ID = "pac",
    ENRLMT_ID = "enid"
  ),
  quality = list(
    `2017` = cheapr::list_combine(
      qpp_ALL,
      list(
        engaged = "engaged_ind",
        `participation type` = "part_opt",
        `small practitioner` = "small_ind",
        `rural clinician` = "rural_ind",
        `hpsa clinician` = "hpsa_ind",
        `ambulatory surgical center` = "asc_ind",
        `hospital-based clinician` = "hospital_ind",
        `non-patient facing` = "non_patient_ind",
        `facility-based` = "facility_ind",
        `extreme hardship` = "extreme_ind",
        `quality improvement bonus` = "qi_score",
        `pi bonus` = "pi_bonus_ind",
        `ia score` = "ia_score",
        `cost score` = "cost_score"
      )
    ),
    `2022` = cheapr::list_combine(qpp_ALL, qpp_22),
    `2023` = cheapr::list_combine(
      qpp_ALL,
      qpp_22,
      list(
        `reporting option` = "report_opt",
        `mips value pathway title` = "mvp_title",
        `received facility score` = "fac_score_ind",
        `cost improvement score` = "ci_score"
      )
    )
  ),
  reassignments = list(
    `Individual First Name` = "first",
    `Individual Last Name` = "last",
    `Individual State Code` = "state",
    `Individual Specialty Description` = "specialty",
    `Individual Total Employer Associations` = "employers",
    `Individual NPI` = "npi",
    `Individual PAC ID` = "pac",
    `Individual Enrollment ID` = "enid",
    `Group Legal Business Name` = "org_name",
    `Group Reassignments and Physician Assistants` = "employees",
    `Group PAC ID` = "org_pac",
    `Group Enrollment ID` = "org_enid",
    `Group State Code` = "org_state"
  ),
  revocations = list(
    ORG_NAME = "org_name",
    FIRST_NAME = "first",
    # MDL_NAME = "middle",
    LAST_NAME = "last",
    ENRLMT_ID = "enid",
    NPI = "npi",
    MULTIPLE_NPI_FLAG = "multi",
    STATE_CD = "state",
    PROVIDER_TYPE_DESC = "prov_desc",
    REVOCATION_RSN = "reason",
    REVOCATION_EFCTV_DT = "start_date",
    REENROLLMENT_BAR_EXPRTN_DT = "end_date"
  ),
  transparency = list(
    Case_ID = "case",
    Hosp_Name = "fac_name",
    Hosp_Address = "address",
    City = "city",
    State = "state",
    Action = "action",
    Date_of_Action = "action_date"
  ),
  utilization = list(
    year = "year",
    Rndrng_NPI = "npi",
    Rndrng_Prvdr_First_Name = "first",
    Rndrng_Prvdr_Last_Org_Name = "last",
    Rndrng_Prvdr_Crdntls = "cred",
    Rndrng_Prvdr_Ent_Cd = "entity",
    Rndrng_Prvdr_St1 = "address",
    Rndrng_Prvdr_St2 = "add_2",
    Rndrng_Prvdr_City = "city",
    Rndrng_Prvdr_State_Abrvtn = "state",
    Rndrng_Prvdr_Zip5 = "zip",
    Rndrng_Prvdr_Type = "specialty",
    Rndrng_Prvdr_Mdcr_Prtcptg_Ind = "part_ind",
    Tot_HCPCS_Cds = "hcpcs",
    Tot_Benes = "patients",
    Tot_Srvcs = "services",
    Tot_Sbmtd_Chrg = "charges",
    Tot_Mdcr_Alowd_Amt = "allowed",
    Tot_Mdcr_Pymt_Amt = "payment",
    Tot_Mdcr_Stdzd_Amt = "standard",
    Bene_Avg_Age = "avg_age",
    Bene_Feml_Cnt = "female",
    Bene_Male_Cnt = "male",
    Bene_Dual_Cnt = "dual",
    Bene_Ndual_Cnt = "ndual",
    Bene_Avg_Risk_Scre = "risk_score"
  ),
  facility = c(
    fac_type = "fac_type",
    RE_ENROLL
  ),
  owner = c(
    fac_type = "fac_type",
    RE_OWNER
  )
)

# fqhc_enroll = RE_ENROLL,
# hha_enroll = RE_ENROLL,
# hospice_enroll = RE_ENROLL,
# rhc_enroll = RE_ENROLL,
# snf_enroll = c(
#   RE_ENROLL,
#   `NURSING HOME PROVIDER NAME` = "nhp_name",
#   `AFFILIATION ENTITY NAME` = "aff_name"
# ),
# fqhc_owner = RE_OWNER2,
# hha_owner = RE_OWNER2,
# hospice_owner = RE_OWNER2,
# rhc_owner = RE_OWNER2,
# hospital_owner = RE_OWNER,
# snf_owner = RE_OWNER
