#' @autoglobal
rename_ <- function(x, nm) {
  if (is.null(nm)) {
    return(x)
  }
  collapse::setrename(x, nm, .nse = FALSE)
  collapse::gv(x, unlist_(nm))
}

#' @noRd
renames <- function(endpoint) {
  switch(
    endpoint,
    affiliations = c(
      provider_first_name = "first",
      provider_last_name = "last",
      provider_middle_name = "middle",
      suff = "suffix",
      npi = "npi",
      ind_pac_id = "pac",
      facility_type = "facility_type",
      facility_affiliations_certification_number = "facility_ccn",
      facility_type_certification_number = "parent_ccn"
    ),
    clinicians = c(
      provider_first_name = "first",
      provider_middle_name = "middle",
      provider_last_name = "last",
      suff = "suffix",
      gndr = "gender",
      cred = "cred",
      med_sch = "school",
      grd_yr = "year",
      pri_spec = "specialty",
      sec_spec_all = "spec_other",
      facility_name = "facility_name",
      npi = "npi",
      ind_pac_id = "pac",
      ind_enrl_id = "enid",
      org_pac_id = "org_pac",
      num_org_mem = "org_mems",
      adr_ln_1 = "add_1",
      adr_ln_2 = "add_2",
      citytown = "city",
      state = "state",
      zip_code = "zip",
      telephone_number = "phone",
      ind_assgn = "ind",
      grp_assgn = "grp",
      telehlth = "tele"
    ),
    hospitals = c(
      `ORGANIZATION NAME` = "org_name",
      `DOING BUSINESS AS NAME` = "dba_name",
      `ENROLLMENT ID` = "enid",
      `ENROLLMENT STATE` = "enid_state",
      `PROVIDER TYPE CODE` = "spec",
      `PROVIDER TYPE TEXT` = "specialty",
      `NPI` = "npi",
      `MULTIPLE NPI FLAG` = "multi",
      `CCN` = "ccn",
      `CAH OR HOSPITAL CCN` = "ccn_2",
      `ASSOCIATE ID` = "pac",
      `INCORPORATION DATE` = "inc_date",
      `INCORPORATION STATE` = "inc_state",
      `ORGANIZATION TYPE STRUCTURE` = "org_type",
      `ORGANIZATION OTHER TYPE TEXT` = "org_text",
      `PROPRIETARY NONPROFIT` = "designation",
      `ADDRESS LINE 1` = "add_1",
      `ADDRESS LINE 2` = "add_2",
      `CITY` = "city",
      `STATE` = "state",
      `ZIP CODE` = "zip",
      `PRACTICE LOCATION TYPE` = "location_type",
      `LOCATION OTHER TYPE TEXT` = "location_text",
      `REH CONVERSION FLAG` = "reh_ind",
      `REH CONVERSION DATE` = "reh_date",
      `SUBGROUP - GENERAL` = "sub_general",
      `SUBGROUP - ACUTE CARE` = "sub_acute",
      `SUBGROUP - ALCOHOL DRUG` = "sub_drug",
      `SUBGROUP - CHILDRENS` = "sub_child",
      `SUBGROUP - LONG-TERM` = "sub_long",
      `SUBGROUP - PSYCHIATRIC` = "sub_psych",
      `SUBGROUP - REHABILITATION` = "sub_rehab",
      `SUBGROUP - SHORT-TERM` = "sub_short",
      `SUBGROUP - SWING-BED APPROVED` = "sub_swing",
      `SUBGROUP - PSYCHIATRIC UNIT` = "sub_psych_unit",
      `SUBGROUP - REHABILITATION UNIT` = "sub_rehab_unit",
      `SUBGROUP - SPECIALTY HOSPITAL` = "sub_specialty",
      `SUBGROUP - OTHER` = "sub_other",
      `SUBGROUP - OTHER TEXT` = "sub_otext"
    ),
    laboratories = c(
      FAC_NAME = "name_1",
      ADDTNL_FAC_NAME = "name_2",
      PRVDR_NUM = "ccn",
      CROSS_REF_PROVIDER_NUMBER = "xref",
      CHOW_CNT = "chow_n",
      CHOW_DT = "chow_date",
      CHOW_PRIOR_DT = "chow_prev",
      ACPTBL_POC_SW = "pos",
      CMPLNC_STUS_CD = "status", # A=IN COMPLIANCE, B=NOT IN COMPLIANCE
      ST_ADR = "add_1",
      ADDTNL_ST_ADR = "add_2",
      PHNE_NUM = "phone_1",
      FAX_PHNE_NUM = "phone_2",
      CITY_NAME = "city",
      STATE_CD = "state",
      RGN_CD = "region",
      ZIP_CD = "zip",
      SSA_STATE_CD = "state_ssa",
      SSA_CNTY_CD = "county_ssa",
      FIPS_STATE_CD = "fips_state",
      FIPS_CNTY_CD = "fips_county",
      STATE_RGN_CD = "state_reg",
      CBSA_CD = "cbsa_cd",
      CBSA_URBN_RRL_IND = "cbsa_ind",
      ELGBLTY_SW = "eligible",
      PGM_TRMNTN_CD = "term_pgm",
      CLIA_TRMNTN_CD = "term_clia",
      APLCTN_TYPE_CD = "apl_type",
      CRTFCT_TYPE_CD = "cert_type",
      GNRL_FAC_TYPE_CD = "fac_type",
      GNRL_CNTL_TYPE_CD = "ownership",
      CRTFCTN_ACTN_TYPE_CD = "cert_action",
      ORGNL_PRTCPTN_DT = "orig_date",
      APLCTN_RCVD_DT = "apl_date",
      CRTFCTN_DT = "cert_date",
      CRTFCT_EFCTV_DT = "eff_date",
      CRTFCT_MAIL_DT = "mail_date",
      TRMNTN_EXPRTN_DT = "term_date",
      A2LA_ACRDTD_CD = "a2la_cred", # X=ACCREDITED
      A2LA_ACRDTD_Y_MATCH_DT = "a2la_date",
      A2LA_ACRDTD_Y_MATCH_SW = "a2la_ind",
      AABB_ACRDTD_CD = "aabb_cred",
      AABB_ACRDTD_Y_MATCH_DT = "aabb_date",
      AABB_ACRDTD_Y_MATCH_SW = "aabb_ind",
      AOA_ACRDTD_CD = "aoa_cred",
      AOA_ACRDTD_Y_MATCH_DT = "aoa_date",
      AOA_ACRDTD_Y_MATCH_SW = "aoa_ind",
      ASHI_ACRDTD_CD = "ashi_cred",
      ASHI_ACRDTD_Y_MATCH_DT = "ashi_date",
      ASHI_ACRDTD_Y_MATCH_SW = "ashi_ind",
      CAP_ACRDTD_CD = "cap_cred",
      CAP_ACRDTD_Y_MATCH_DT = "cap_date",
      CAP_ACRDTD_Y_MATCH_SW = "cap_ind",
      COLA_ACRDTD_CD = "cola_cred",
      COLA_ACRDTD_Y_MATCH_DT = "cola_date",
      COLA_ACRDTD_Y_MATCH_SW = "cola_ind",
      JCAHO_ACRDTD_CD = "jcaho_cred",
      JCAHO_ACRDTD_Y_MATCH_DT = "jcaho_date",
      JCAHO_ACRDTD_Y_MATCH_SW = "jcaho_ind",
      CLIA_MDCR_NUM = "clia_88",
      ACRDTN_SCHDL_CD = "acrd_sched",
      FORM_1557_CRTFCT_SCHDL_CD = "cert_sched",
      FORM_1557_CMPLNC_SCHDL_CD = "comp_sched",
      FORM_1557_TEST_VOL_CNT = "survey_vol",
      FORM_116_ACRDTD_TEST_VOL_CNT = "acrd_vol",
      FORM_116_TEST_VOL_CNT = "comp_vol",
      PPMP_TEST_VOL_CNT = "ppm_vol",
      WVD_TEST_VOL_CNT = "waive_vol",
      DRCTLY_AFLTD_LAB_CNT = "affiliated",
      MLT_SITE_EXCPTN_SW = "multi",
      HOSP_LAB_EXCPTN_SW = "hosp",
      NON_PRFT_EXCPTN_SW = "nonprof",
      LAB_TEMP_TSTG_SITE_SW = "temp",
      LAB_SITE_CNT = "sites",
      RELATED_PROVIDER_NUMBER = "related_num",
      SHR_LAB_SW = "shared_lab",
      SHARED_LAB_XREF_NUMBER = "shared_num",
      FY_END_MO_DAY_CD = "fyend",

      # PRVDR_CTGRY_CD = "prv_cat", # 22=CLIA Laboratory
      # PRVDR_CTGRY_SBTYP_CD = "prv_type", # 01=CLIA88 Laboratory
      # CURRENT_CLIA_LAB_CLSFCTN_CD = "cls0",
      # CLIA_LAB_CLASSIFICATION_CD_1 = "cls1",
      # CLIA_LAB_CLASSIFICATION_CD_2 = "cls2",
      # CLIA_LAB_CLASSIFICATION_CD_3 = "cls3",
      # CLIA_LAB_CLASSIFICATION_CD_4 = "cls4",
      # CLIA_LAB_CLASSIFICATION_CD_5 = "cls5",
      # CLIA_LAB_CLASSIFICATION_CD_6 = "cls6",
      # CLIA_LAB_CLASSIFICATION_CD_7 = "cls7",
      # CLIA_LAB_CLASSIFICATION_CD_8 = "cls8",
      # CLIA_LAB_CLASSIFICATION_CD_9 = "cls9",
      # CLIA_LAB_CLASSIFICATION_CD_10 = "cls10",
      # AFFILIATED_PROVIDER_NUMBER_1 = "aff_1",
      # AFFILIATED_PROVIDER_NUMBER_2 = "aff_2",
      # AFFILIATED_PROVIDER_NUMBER_3 = "aff_3",
      # AFFILIATED_PROVIDER_NUMBER_4 = "aff_4",
      # AFFILIATED_PROVIDER_NUMBER_5 = "aff_5",
      # AFFILIATED_PROVIDER_NUMBER_6 = "aff_6",
      # AFFILIATED_PROVIDER_NUMBER_7 = "aff_7",
      # AFFILIATED_PROVIDER_NUMBER_8 = "aff_8",
      INTRMDRY_CARR_CD = "mac_curr",
      INTRMDRY_CARR_PRIOR_CD = "mac_prev",
      MDCD_VNDR_NUM = "vend",
      SKLTN_REC_SW = "skeleton" # Only provider categories 01, 17, 19, 21, 22 can have skeleton providers
    ),
    providers = c(
      FIRST_NAME = "first",
      MDL_NAME = "middle",
      LAST_NAME = "last",
      ORG_NAME = "org_name",
      STATE_CD = "state",
      PROVIDER_TYPE_CD = "spec",
      PROVIDER_TYPE_DESC = "specialty",
      NPI = "npi",
      MULTIPLE_NPI_FLAG = "multi",
      PECOS_ASCT_CNTL_ID = "pac",
      ENRLMT_ID = "enid"
    ),
    opt_out = c(
      NPI = "npi",
      `First Name` = "first",
      `Last Name` = "last",
      Specialty = "specialty",
      `Optout Effective Date` = "date_start",
      `Optout End Date` = "date_end",
      `Last updated` = "last_update",
      `First Line Street Address` = "add_1",
      `Second Line Street Address` = "add_2",
      `City Name` = "city",
      `State Code` = "state",
      `Zip code` = "zip",
      `Eligible to Order and Refer` = "order_refer"
    ),
    order_refer = c(
      NPI = "npi",
      FIRST_NAME = "first",
      LAST_NAME = "last",
      PARTB = "part_b",
      DME = "dme",
      HHA = "hha",
      PMD = "pmd",
      HOSPICE = "hospice"
    ),
    reassignments = c(
      `Individual First Name` = "first",
      `Individual Last Name` = "last",
      `Individual State Code` = "state",
      `Individual Specialty Description` = "specialty",
      `Individual Total Employer Associations` = "ind_assoc",
      `Individual NPI` = "npi",
      `Individual PAC ID` = "pac",
      `Individual Enrollment ID` = "enid",
      `Group Legal Business Name` = "org_name",
      `Group Reassignments and Physician Assistants` = "org_assign",
      `Group PAC ID` = "org_pac",
      `Group Enrollment ID` = "org_enid",
      `Group State Code` = "org_state",
      `Record Type` = "type"
    ),
    cli::cli_abort("{.arg endpoint} {.val {endpoint}} invalid.")
  )
}
