#' @noRd
renames <- function(endpoint) {
  switch(
    endpoint,
    affiliations = c(
      npi = "npi",
      ind_pac_id = "pac",
      provider_last_name = "last",
      provider_first_name = "first",
      provider_middle_name = "middle",
      suff = "suffix",
      facility_type = "facility_type",
      facility_affiliations_certification_number = "facility_ccn",
      facility_type_certification_number = "parent_ccn"
    ),
    clinicians = c(
      npi = "npi",
      ind_pac_id = "pac",
      ind_enrl_id = "enid",
      provider_last_name = "last",
      provider_first_name = "first",
      provider_middle_name = "middle",
      suff = "suffix",
      gndr = "gender",
      cred = "credential",
      med_sch = "grad_school",
      grd_yr = "grad_year",
      pri_spec = "specialty",
      sec_spec_all = "spec_other",
      telehlth = "telehealth",
      facility_name = "facility_name",
      org_pac_id = "org_pac",
      num_org_mem = "org_mem",
      adr_ln_1 = "add_1",
      adr_ln_2 = "add_2",
      citytown = "city",
      state = "state",
      zip_code = "zip",
      telephone_number = "phone",
      ind_assgn = "ind_par",
      grp_assgn = "grp_par"
    ),
    providers = c(
      NPI = "npi",
      MULTIPLE_NPI_FLAG = "multi",
      PECOS_ASCT_CNTL_ID = "pac",
      ENRLMT_ID = "enid",
      PROVIDER_TYPE_CD = "spec_code",
      PROVIDER_TYPE_DESC = "spec_desc",
      STATE_CD = "state",
      LAST_NAME = "last",
      FIRST_NAME = "first",
      MDL_NAME = "middle",
      ORG_NAME = "org_name"
    ),
    opt_out = c(
      NPI = "npi",
      `First Name` = "first",
      `Last Name` = "last",
      Specialty = "specialty",
      `Optout Effective Date` = "date_start",
      `Optout End Date` = "date_end",
      `Last updated` = "last_update",
      `First Line Street Address` = "add1",
      `Second Line Street Address` = "add2",
      `City Name` = "city",
      `State Code` = "state",
      `Zip code` = "zip",
      `Eligible to Order and Refer` = "order_refer"
    ),
    order_refer = c(
      NPI = "npi",
      FIRST_NAME = "first",
      LAST_NAME = "last",
      PARTB = "part_b",
      DME = "dme",
      HHA = "hha",
      PMD = "pmd",
      HOSPICE = "hospice"
    ),
    # hospitals = m("f6f6505c-e8b0-4d57-b258-e2b94133aaf2"),
    # laboratories = m("d3eb38ac-d8e9-40d3-b7b7-6205d3d1dc16"),
    reassignments = c(
      `Individual NPI` = "npi",
      `Individual PAC ID` = "pac",
      `Individual Enrollment ID` = "enid",
      `Individual First Name` = "first",
      `Individual Last Name` = "last",
      `Individual State Code` = "state",
      `Individual Specialty Description` = "specialty",
      `Group Reassignments and Physician Assistants` = "reassignments",
      `Group Legal Business Name` = "org_name",
      `Group PAC ID` = "org_pac",
      `Group Enrollment ID` = "org_enid",
      `Group State Code` = "org_state",
      `Individual Total Employer Associations` = "associations",
      `Record Type` = "type"
    ),
    cli::cli_abort("{.arg endpoint} {.val {endpoint}} not recognized")
  )
}
