#' @noRd
set_rename <- function(x) {
  collapse::setrename(x, RE_NAME[[class(x)[1]]], .nse = FALSE)
  replace_nz(x)
}

#' @noRd
get_columns <- function(x) {
  collapse::gv(x, unlist_(RE_NAME[[class(x)[1]]]))
}

#' @noRd
qpp_ALL = list(
  year = "year",
  npi = "npi",
  `practice state or us territory` = "state",
  `practice size` = "size",
  `clinician specialty` = "specialty",
  `years in medicare` = "years",
  `medicare patients` = "patients",
  services = "services",
  `allowed charges` = "charges",
  `final score` = "final_score",
  `payment adjustment percentage` = "adjustment",
  `promoting interoperability (pi) category score` = "pi_score",
  `quality category score` = "qa_score",
  `complex patient bonus` = "complex_bonus",
  `opted into mips` = "opted_ind"
)

#' @noRd
qpp_22 = list(
  `clinician type` = "cred",
  `participation option` = "partype",
  `dual eligibility ratio` = "dual_ratio",
  `quality improvement score` = "qi_score",
  `small practice bonus` = "small_bonus",
  `improvement activities (ia) category score` = "ia_score",
  `cost category score` = "cost_score",
  `non-reporting` = "non_report_ind",
  `safety-net status` = "safety_ind",
  `extreme uncontrollable circumstance (euc)` = "extreme_ind",
  `small practice status` = "small_ind",
  `rural status` = "rural_ind",
  `health professional shortage area status` = "hpsa_ind",
  `ambulatory surgical center-based status` = "asc_ind",
  `hospital-based status` = "hospital_ind",
  `non-patient facing status` = "non_patient_ind",
  `facility-based status` = "facility_ind",
  `ia credit` = "ia_credit_ind"
)

#' @noRd
RE_NAME = list(
  affiliations = list(
    provider_first_name = "first",
    provider_last_name = "last",
    npi = "npi",
    ind_pac_id = "pac",
    facility_type = "fac_type",
    facility_affiliations_certification_number = "ccn",
    facility_type_certification_number = "parent_ccn"
  ),
  clia = list(
    FAC_NAME = "name",
    ADDTNL_FAC_NAME = "fac_2",
    PRVDR_NUM = "ccn",
    CLIA_MDCR_NUM = "clia",
    CLIA_TRMNTN_CD = "status",
    DRCTLY_AFLTD_LAB_CNT = "labs",
    LAB_SITE_CNT = "sites",
    CRTFCT_TYPE_CD = "certificate",
    ST_ADR = "address",
    ADDTNL_ST_ADR = "add_2",
    GNRL_FAC_TYPE_CD = "fac_type",
    GNRL_CNTL_TYPE_CD = "owner",
    CRTFCTN_ACTN_TYPE_CD = "action",
    CRTFCTN_DT = "cert_date",
    CRTFCT_EFCTV_DT = "eff_date",
    TRMNTN_EXPRTN_DT = "term_date",
    A2LA_ACRDTD_Y_MATCH_DT = "acr_a2la_date",
    AABB_ACRDTD_Y_MATCH_DT = "acr_aabb_date",
    AOA_ACRDTD_Y_MATCH_DT = "acr_aoa_date",
    ASHI_ACRDTD_Y_MATCH_DT = "acr_ashi_date",
    CAP_ACRDTD_Y_MATCH_DT = "acr_cap_date",
    COLA_ACRDTD_Y_MATCH_DT = "acr_cola_date",
    JCAHO_ACRDTD_Y_MATCH_DT = "acr_jcaho_date",
    MLT_SITE_EXCPTN_SW = "site_multi",
    HOSP_LAB_EXCPTN_SW = "hosp_multi",
    NON_PRFT_EXCPTN_SW = "non_multi",
    LAB_TEMP_TSTG_SITE_SW = "tmp_multi",
    ELGBLTY_SW = "elig",
    CITY_NAME = "city",
    STATE_CD = "state",
    ZIP_CD = "zip"
  ),
  clinician = list(
    npi = "npi",
    ind_pac_id = "pac",
    ind_enrl_id = "enid",
    provider_first_name = "first",
    provider_last_name = "last",
    gndr = "gender",
    cred = "cred",
    med_sch = "school",
    grd_yr = "year",
    pri_spec = "specialty",
    sec_spec_all = "spec_other",
    facility_name = "org_name",
    org_pac_id = "org_pac",
    num_org_mem = "members",
    adr_ln_1 = "address",
    adr_ln_2 = "add_2",
    citytown = "city",
    state = "state",
    zip_code = "zip"
  ),
  dialysis = list(
    cms_certification_number_ccn = "ccn",
    facility_name = "name",
    five_star = "rating",
    network = "network",
    profit_or_nonprofit = "status",
    chain_organization = "org_name",
    certification_date = "cert_date",
    address_line_1 = "address",
    address_line_2 = "add_2",
    citytown = "city",
    state = "state",
    zip_code = "zip",
    countyparish = "county"
  ),
  facility = c(
    fac_type = "fac_type",
    CCN = "ccn",
    NPI = "npi",
    `ASSOCIATE ID` = "pac",
    `ENROLLMENT ID` = "enid",
    `MULTIPLE NPI FLAG` = "multi",
    `ORGANIZATION NAME` = "org_name",
    `DOING BUSINESS AS NAME` = "org_dba",
    `INCORPORATION DATE` = "inc_date",
    `ORGANIZATION TYPE STRUCTURE` = "org_type",
    `ORGANIZATION OTHER TYPE TEXT` = "org_otxt",
    PROPRIETARY_NONPROFIT = "status",
    `ADDRESS LINE 1` = "address",
    `ADDRESS LINE 2` = "add_2",
    CITY = "city",
    STATE = "state",
    `ZIP CODE` = "zip"
  ),
  hospital = list(
    `ORGANIZATION NAME` = "org_name",
    `DOING BUSINESS AS NAME` = "org_dba",
    CCN = "ccn",
    NPI = "npi",
    `ASSOCIATE ID` = "pac",
    `ENROLLMENT ID` = "enid",
    `MULTIPLE NPI FLAG` = "multi",
    `INCORPORATION DATE` = "inc_date",
    `ORGANIZATION TYPE STRUCTURE` = "org_type",
    `ORGANIZATION OTHER TYPE TEXT` = "org_otxt",
    `PROPRIETARY NONPROFIT` = "status",
    `ADDRESS LINE 1` = "address",
    `ADDRESS LINE 2` = "add_2",
    CITY = "city",
    STATE = "state",
    `ZIP CODE` = "zip",
    `PRACTICE LOCATION TYPE` = "loc_type",
    `LOCATION OTHER TYPE TEXT` = "loc_otxt",
    `PROVIDER TYPE CODE` = "prov_type",
    `REH CONVERSION FLAG` = "reh_ind",
    `SUBGROUP - ACUTE CARE` = "acute_ind",
    `SUBGROUP - GENERAL` = "gen_ind",
    `SUBGROUP - SPECIALTY HOSPITAL` = "spec_ind",
    `SUBGROUP - ALCOHOL DRUG` = "adu_ind",
    `SUBGROUP - CHILDRENS` = "child_ind",
    `SUBGROUP - LONG-TERM` = "ltc_ind",
    `SUBGROUP - PSYCHIATRIC` = "psy_ind",
    `SUBGROUP - REHABILITATION` = "irf_ind",
    `SUBGROUP - SHORT-TERM` = "stc_ind",
    `SUBGROUP - SWING-BED APPROVED` = "sba_ind",
    `SUBGROUP - PSYCHIATRIC UNIT` = "psu_ind",
    `SUBGROUP - REHABILITATION UNIT` = "iru_ind",
    `SUBGROUP - OTHER` = "other_ind",
    `SUBGROUP - OTHER TEXT` = "other_otxt"
  ),
  hospital2 = list(
    facility_id = "ccn",
    facility_name = "org_name",
    hospital_type = "prov_type",
    hospital_ownership = "status",
    hospital_overall_rating = "rating",
    address = "address",
    citytown = "city",
    state = "state",
    zip_code = "zip",
    countyparish = "county"
  ),
  opted_out = list(
    NPI = "npi",
    `First Name` = "first",
    `Last Name` = "last",
    Specialty = "specialty",
    `Optout Effective Date` = "start_date",
    `Optout End Date` = "end_date",
    `Last updated` = "updated",
    `First Line Street Address` = "address",
    `Second Line Street Address` = "add_2",
    `City Name` = "city",
    `State Code` = "state",
    `Zip code` = "zip",
    `Eligible to Order and Refer` = "order_refer"
  ),
  order_refer = list(
    NPI = "npi",
    FIRST_NAME = "first",
    LAST_NAME = "last",
    PARTB = "ptb_ind",
    DME = "dme_ind",
    HHA = "hha_ind",
    PMD = "pmd_ind",
    HOSPICE = "hsp_ind"
  ),
  pending = list(
    prov_type = "prov_type",
    NPI = "npi",
    FIRST_NAME = "first",
    LAST_NAME = "last"
  ),
  providers = list(
    NPI = "npi",
    PECOS_ASCT_CNTL_ID = "pac",
    ENRLMT_ID = "enid",
    PROVIDER_TYPE_CD = "prov_type",
    PROVIDER_TYPE_DESC = "prov_desc",
    ORG_NAME = "org_name",
    FIRST_NAME = "first",
    LAST_NAME = "last",
    STATE_CD = "state",
    MULTIPLE_NPI_FLAG = "multi"
  ),
  quality = list(
    `2017` = cheapr::list_combine(
      qpp_ALL,
      list(
        `participation type` = "partype",
        `quality improvement bonus` = "qi_score",
        `ia score` = "ia_score",
        `cost score` = "cost_score",
        engaged = "engaged_ind",
        `small practitioner` = "small_ind",
        `rural clinician` = "rural_ind",
        `hpsa clinician` = "hpsa_ind",
        `ambulatory surgical center` = "asc_ind",
        `hospital-based clinician` = "hospital_ind",
        `non-patient facing` = "non_patient_ind",
        `facility-based` = "facility_ind",
        `pi bonus` = "pi_bonus_ind",
        `extreme hardship` = "extreme_ind"
      )
    ),
    `2022` = cheapr::list_combine(qpp_ALL, qpp_22),
    `2023` = cheapr::list_combine(
      qpp_ALL,
      qpp_22,
      list(
        `reporting option` = "reportype",
        `mips value pathway title` = "mvp",
        `cost improvement score` = "ci_score",
        `received facility score` = "fac_score_ind"
      )
    )
  ),
  reassigned = list(
    `Individual NPI` = "npi",
    `Individual PAC ID` = "pac",
    `Individual Enrollment ID` = "enid",
    `Individual First Name` = "first",
    `Individual Last Name` = "last",
    `Individual State Code` = "state",
    `Individual Specialty Description` = "specialty",
    `Individual Total Employer Associations` = "memberships",
    `Group PAC ID` = "org_pac",
    `Group Enrollment ID` = "org_enid",
    `Group Legal Business Name` = "org_name",
    `Group Reassignments and Physician Assistants` = "members",
    `Group State Code` = "org_state"
  ),
  revoked = list(
    ORG_NAME = "org",
    FIRST_NAME = "first",
    LAST_NAME = "last",
    ENRLMT_ID = "enid",
    NPI = "npi",
    MULTIPLE_NPI_FLAG = "multi",
    STATE_CD = "state",
    PROVIDER_TYPE_DESC = "prov_desc",
    REVOCATION_RSN = "reason",
    REVOCATION_EFCTV_DT = "start_date",
    REENROLLMENT_BAR_EXPRTN_DT = "end_date"
  ),
  transparency = list(
    Case_ID = "case",
    Hosp_Name = "name",
    Hosp_Address = "address",
    City = "city",
    State = "state",
    Action = "action",
    Date_of_Action = "action_date"
  ),
  utilization = list(
    year = "year",
    Rndrng_NPI = "npi",
    Rndrng_Prvdr_Ent_Cd = "entity",
    Rndrng_Prvdr_Mdcr_Prtcptg_Ind = "par",
    Tot_HCPCS_Cds = "hcpcs",
    Tot_Benes = "patients",
    Tot_Srvcs = "services",
    Tot_Sbmtd_Chrg = "charges",
    Tot_Mdcr_Alowd_Amt = "allowed",
    Tot_Mdcr_Pymt_Amt = "payment",
    Bene_Avg_Age = "avg_age",
    Bene_Avg_Risk_Scre = "avg_risk",
    Bene_Dual_Cnt = "dual",
    Bene_Ndual_Cnt = "ndual",
    Rndrng_Prvdr_First_Name = "first",
    Rndrng_Prvdr_Last_Org_Name = "last",
    Rndrng_Prvdr_Crdntls = "cred",
    Rndrng_Prvdr_Type = "specialty",
    Rndrng_Prvdr_St1 = "address",
    Rndrng_Prvdr_St2 = "add_2",
    Rndrng_Prvdr_City = "city",
    Rndrng_Prvdr_State_Abrvtn = "state",
    Rndrng_Prvdr_Zip5 = "zip"
  ),
  services = list(
    year = "year",
    Rndrng_NPI = "npi",
    Rndrng_Prvdr_Ent_Cd = "entity",
    Rndrng_Prvdr_First_Name = "first",
    Rndrng_Prvdr_Last_Org_Name = "last",
    Rndrng_Prvdr_Crdntls = "cred",
    Rndrng_Prvdr_Type = "specialty",
    Rndrng_Prvdr_Mdcr_Prtcptg_Ind = "par",
    HCPCS_Cd = "hcpcs",
    HCPCS_Desc = "desc",
    HCPCS_Drug_Ind = "drug",
    Place_Of_Srvc = "pos",
    Tot_Benes = "patients",
    Tot_Srvcs = "services",
    Tot_Bene_Day_Srvcs = "day_services",
    Avg_Sbmtd_Chrg = "charge",
    Avg_Mdcr_Alowd_Amt = "allowed",
    Avg_Mdcr_Pymt_Amt = "payment",
    Avg_Mdcr_Stdzd_Amt = "standard",
    Rndrng_Prvdr_St1 = "address",
    Rndrng_Prvdr_St2 = "add_2",
    Rndrng_Prvdr_City = "city",
    Rndrng_Prvdr_State_Abrvtn = "state",
    Rndrng_Prvdr_Zip5 = "zip"
  ),
  geography = list(
    year = "year",
    # Rndrng_Prvdr_Geo_Lvl = "level",
    Rndrng_Prvdr_Geo_Desc = "state",
    HCPCS_Cd = "hcpcs",
    HCPCS_Desc = "desc",
    HCPCS_Drug_Ind = "drug",
    Place_Of_Srvc = "pos",
    Tot_Rndrng_Prvdrs = "providers",
    Tot_Benes = "patients",
    Tot_Srvcs = "services",
    Avg_Sbmtd_Chrg = "charge",
    Avg_Mdcr_Alowd_Amt = "allowed",
    Avg_Mdcr_Pymt_Amt = "payment",
    Avg_Mdcr_Stdzd_Amt = "avg_standard"
  ),
  owner = list(
    `ORGANIZATION NAME` = "name",
    fac_type = "type",
    `ASSOCIATE ID` = "pac",
    `ENROLLMENT ID` = "enid",
    `ASSOCIATE ID - OWNER` = "own_pac",
    `ORGANIZATION NAME - OWNER` = "own_org",
    `DOING BUSINESS AS NAME - OWNER` = "own_dba",
    `ASSOCIATION DATE - OWNER` = "own_date",
    `TITLE - OWNER` = "own_title",
    `FIRST NAME - OWNER` = "own_first",
    `LAST NAME - OWNER` = "own_last",
    `PERCENTAGE OWNERSHIP` = "own_pct",
    `ROLE CODE - OWNER` = "own_role",
    `ADDRESS LINE 1 - OWNER` = "address",
    `ADDRESS LINE 2 - OWNER` = "add_2",
    `CITY - OWNER` = "city",
    `STATE - OWNER` = "state",
    `ZIP CODE - OWNER` = "zip",
    `CREATED FOR ACQUISITION - OWNER` = "acq_ind",
    `CORPORATION - OWNER` = "corp_ind",
    `LLC - OWNER` = "llc_ind",
    `MEDICAL PROVIDER SUPPLIER - OWNER` = "mps_ind",
    `MANAGEMENT SERVICES COMPANY - OWNER` = "msr_ind",
    `MEDICAL STAFFING COMPANY - OWNER` = "mst_ind",
    `HOLDING COMPANY - OWNER` = "hld_ind",
    `INVESTMENT FIRM - OWNER` = "inv_ind",
    `FINANCIAL INSTITUTION - OWNER` = "fin_ind",
    `CONSULTING FIRM - OWNER` = "con_ind",
    `FOR PROFIT - OWNER` = "fp_ind",
    `NON PROFIT - OWNER` = "np_ind",
    `OTHER TYPE - OWNER` = "oth_ind",
    `OTHER TYPE TEXT - OWNER` = "own_otxt"
  ),
  inpatient = list(
    year = "year",
    Rndrng_Prvdr_CCN = "ccn",
    Rndrng_Prvdr_Org_Name = "org_name",
    Rndrng_Prvdr_St = "address",
    Rndrng_Prvdr_City = "city",
    Rndrng_Prvdr_State_Abrvtn = "state",
    Rndrng_Prvdr_Zip5 = "zip",
    Tot_Benes = "patients",
    Tot_Dschrgs = "discharges",
    Tot_Days = "days",
    Tot_Cvrd_Days = "covered",
    Tot_Submtd_Cvrd_Chrg = "charge",
    Tot_Pymt_Amt = "payment",
    Tot_Mdcr_Pymt_Amt = "mdcpay",
    Bene_Avg_Age = "avg_age",
    Bene_Avg_Risk_Scre = "avg_risk",
    Bene_Dual_Cnt = "dual",
    Bene_Ndual_Cnt = "ndual"
  ),
  outpatient = list(
    year = "year",
    Rndrng_Prvdr_CCN = "ccn",
    Rndrng_Prvdr_Org_Name = "org_name",
    Rndrng_Prvdr_St = "address",
    Rndrng_Prvdr_City = "city",
    Rndrng_Prvdr_State_Abrvtn = "state",
    Rndrng_Prvdr_Zip5 = "zip",
    APC_Cd = "apc",
    APC_Desc = "desc",
    Bene_Cnt = "patients",
    CAPC_Srvcs = "services",
    Outlier_Srvcs = "outliers",
    Avg_Tot_Sbmtd_Chrgs = "charge",
    Avg_Mdcr_Alowd_Amt = "allowed",
    Avg_Mdcr_Pymt_Amt = "payment",
    Avg_Mdcr_Outlier_Amt = "outpay"
  ),
  ambulatory = list(
    facility_id = "ccn",
    facility_name = "name",
    address = "address",
    citytown = "city",
    state = "state",
    zip_code = "zip",
    countyparish = "county",
    number_of_sampled_patients = "patients",
    number_of_completed_surveys = "surveys",
    survey_response_rate_percent = "response",
    patients_rating_of_the_facility_linear_mean_score = "rating"
  ),
  longterm = list(
    cms_certification_number_ccn = "ccn",
    provider_name = "name",
    address_line_1 = "address",
    address_line_2 = "add_2",
    citytown = "city",
    state = "state",
    zip_code = "zip",
    countyparish = "county",
    ownership_type = "own_type",
    certification_date = "cert_date",
    total_number_of_beds = "beds"
  ),
  mspb = list(
    facility_id = "ccn",
    facility_name = "name",
    score = "score",
    address = "address",
    citytown = "city",
    state = "state",
    zip_code = "zip",
    countyparish = "county"
  ),
  msbc = list(
    facility_id = "ccn",
    facility_name = "name",
    state = "state",
    period = "period",
    claim_type = "claim",
    avg_spndg_per_ep_hospital = "avg_hosp",
    avg_spndg_per_ep_state = "avg_state",
    avg_spndg_per_ep_national = "avg_natl",
    percent_of_spndg_hospital = "pct_hosp",
    percent_of_spndg_state = "pct_state",
    percent_of_spndg_national = "pct_natl"
  ),
  rehab = list(
    cms_certification_number_ccn = "ccn",
    provider_name = "name",
    address_line_1 = "address",
    address_line_2 = "add_2",
    citytown = "city",
    state = "state",
    zip_code = "zip",
    countyparish = "county",
    ownership_type = "own_type",
    certification_date = "cert_date"
  ),
  nursing = list(
    cms_certification_number_ccn = "ccn",
    provider_name = "name",
    provider_address = "address",
    citytown = "city",
    state = "state",
    zip_code = "zip",
    countyparish = "county",
    ownership_type = "own_type",
    provider_type = "prov_type",
    legal_business_name = "org_dba",
    chain_name = "chain",
    date_first_approved_to_provide_medicare_and_medicaid_services = "cert_date",
    number_of_facilities_in_chain = "facilities",
    chain_average_overall_5star_rating = "chain_rating",
    number_of_certified_beds = "beds",
    average_number_of_residents_per_day = "avg_res_day",
    overall_rating = "rating",
    number_of_fines = "fines",
    number_of_payment_denials = "denials",
    total_amount_of_fines_in_dollars = "fine_amt",
    total_number_of_penalties = "penalties",
    latitude = "lat",
    longitude = "lon"
  ),
  psych = list(
    facility_id = "ccn",
    facility_name = "name",
    address = "address",
    citytown = "city",
    state = "state",
    zip_code = "zip",
    countyparish = "county"
  ),
  supplier = list(
    provider_id = "prov_id",
    acceptsassignement = "par",
    participationbegindate = "start_date",
    businessname = "org_dba",
    practicename = "org_name",
    practiceaddress1 = "address",
    practiceaddress2 = "add_2",
    practicecity = "city",
    practicestate = "state",
    practicezip9code = "zip",
    specialitieslist = "specialty",
    providertypelist = "prov_type",
    supplieslist = "supplies",
    latitude = "lat",
    longitude = "lon",
    is_contracted_for_cba = "cba"
  ),
  veteran = list(
    facility_id = "ccn",
    facility_name = "name",
    address = "address",
    citytown = "city",
    state = "state",
    zip_code = "zip",
    countyparish = "county",
    hospital_type = "prov_type",
    hospital_ownership = "own_type",
    emergency_services = "emergency",
    hospital_overall_rating = "rating"
  )
)

# snf_enroll = c(
#   facility,
#   `NURSING HOME PROVIDER NAME` = "nhp_name",
#   `AFFILIATION ENTITY NAME` = "aff_name"
# )

# RE_OWNER2 = c(
#   owner,
#   `PRIVATE EQUITY COMPANY - OWNER` = "pe_ind",
#   `REIT - OWNER` = "reit_ind",
#   `CHAIN HOME OFFICE - OWNER` = "cho_ind",
#   `OWNED BY ANOTHER ORG OR IND - OWNER` = "ano_ind"
# )
#
# fqhc_owner, hha_owner, hospice_owner,
# rhc_owner, hospital_owner, snf_owner
